// One Piece Character Database - Actualizada con 168 personajes

export interface AnimeCharacter {
  id: string;
  name: string;
  nameEnglish?: string;
  anime: string;
  animeId: string;
  crew: string;
  imageUrl: string;
  description: string;
  
  // GAME CATEGORIES - Boolean (SI/NO)
  haki: boolean;                    // ¿Tiene haki?
  
  // GAME CATEGORIES - Specific Values (respuestas específicas)
  recompensa: number | null;        // Recompensa (null = sin recompensa)
  origen: string;                   // Lugar de origen
  tipo_haki: string[];             // Tipos de haki que posee
  fruta_diablo: string | null;     // Nombre de la fruta del diablo (null = no tiene)
  
  // DISPLAY-ONLY (solo para páginas de personajes, NO para juegos)
  element?: string;
  role?: 'main' | 'supporting';
  abilities?: string[];
}

export const ANIME_CHARACTERS: AnimeCharacter[] = [
  {
    id: "op-absalom",
    name: "Absalom",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark Pirates",
    imageUrl: "/images/characters/op-absalom.jpg",
    description: "Zombi general de Thriller Bark con la fruta de la invisibilidad",
    haki: false,
    recompensa: null,
    origen: "Grand Line",
    tipo_haki: [],
    fruta_diablo: "Suke Suke no Mi",
    element: "Invisible",
    role: "supporting",
    abilities: ["Invisibilidad", "Fuerza aumentada", "Liderazgo de zombis"]
  },
  {
    id: "op-ace",
    name: "Ace",
    anime: "One Piece", 
    animeId: "onepiece",
    crew: "Piratas de Barbablanca",
    imageUrl: "/images/characters/op-ace.jpg",
    description: "Comandante de la 2ª División de Barbablanca, hermano de Luffy",
    haki: true,
    recompensa: 550000000,
    origen: "Baterilla",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Mera Mera no Mi",
    element: "Fire",
    role: "main",
    abilities: ["Puño de Fuego", "Haki del Conquistador", "Comandante División"]
  },
  {
    id: "op-akainu",
    name: "Akainu",
    anime: "One Piece",
    animeId: "onepiece", 
    crew: "Marina",
    imageUrl: "/images/characters/op-akainu.jpg",
    description: "Almirante de la Flota de la Marina, usuario de magma",
    haki: true,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Magu Magu no Mi",
    element: "Magma",
    role: "supporting",
    abilities: ["Puño de Magma", "Justicia Absoluta", "Liderazgo Marina"]
  },
  {
    id: "op-alvida",
    name: "Alvida",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Buggy's Delivery", 
    imageUrl: "/images/characters/op-alvida.jpg",
    description: "Capitana pirata, primera enemiga de Luffy",
    haki: false,
    recompensa: 5000000,
    origen: "East Blue",
    tipo_haki: [],
    fruta_diablo: "Sube Sube no Mi",
    element: "Smooth",
    role: "supporting", 
    abilities: ["Piel resbaladiza", "Fuerza bruta", "Liderazgo pirata"]
  },
  {
    id: "op-aokiji",
    name: "Aokiji",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-aokiji.jpg", 
    description: "Ex-Almirante Marina, ahora afiliado a Kurohige",
    haki: true,
    recompensa: null,
    origen: "South Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Hie Hie no Mi",
    element: "Ice",
    role: "supporting",
    abilities: ["Ice Age", "Justicia Perezosa", "Fuerza Almirante"]
  },
  {
    id: "op-apoo",
    name: "Scratchmen Apoo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "On Air Pirates",
    imageUrl: "/images/characters/op-apoo.jpg",
    description: "Capitán de los Piratas On Air, miembro de la Peor Generación",
    haki: false,
    recompensa: 350000000,
    origen: "Grand Line",
    tipo_haki: [],
    fruta_diablo: "Oto Oto no Mi",
    element: "Sound",
    role: "supporting",
    abilities: ["Ataques sónicos", "Música", "Liderazgo pirata"]
  },
  {
    id: "op-arlong",
    name: "Arlong",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Arlong Pirates",
    imageUrl: "/images/characters/op-arlong.jpg",
    description: "Capitán hombre-pez, tirano de Cocoyasi",
    haki: false,
    recompensa: 20000000,
    origen: "Isla Gyojin",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Water",
    role: "supporting",
    abilities: ["Fuerza hombre-pez", "Dientes de sierra", "Armas dentales"]
  },
  {
    id: "op-augur",
    name: "Van Augur",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-augur.jpg",
    description: "Francotirador de los Piratas de Kurohige",
    haki: true,
    recompensa: 64000000,
    origen: "Desconocido",
    tipo_haki: ["Observacion"],
    fruta_diablo: "Wapu Wapu no Mi",
    element: "Gun",
    role: "supporting",
    abilities: ["Francotiro extremo", "Teletransporte", "Observación avanzada"]
  },
  {
    id: "op-bellamy",
    name: "Bellamy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bellamy Pirates",
    imageUrl: "/images/characters/op-bellamy.jpg",
    description: "Capitán Piratas de Bellamy, seguidor de Doflamingo",
    haki: false,
    recompensa: 195000000,
    origen: "North Blue",
    tipo_haki: [],
    fruta_diablo: "Bane Bane no Mi",
    element: "Spring",
    role: "supporting",
    abilities: ["Salto de resorte", "Impacto elástico", "Liderazgo pirata"]
  },
  {
    id: "op-bellemere",
    name: "Bell-mère",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-bellemere.jpg",
    description: "Ex-marina, madre adoptiva de Nami y Nojiko",
    haki: false,
    recompensa: null,
    origen: "Cocoyasi",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Entrenamiento militar", "Cultivo", "Amor maternal"]
  },
  {
    id: "op-ben",
    name: "Ben Beckman",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Pelirrojo",
    imageUrl: "/images/characters/op-ben.jpg",
    description: "Primer oficial de Shanks, intelectual de alto nivel",
    haki: true,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Estrategia", "Armamento", "Liderazgo"]
  },
  {
    id: "op-bepo",
    name: "Bepo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Heart",
    imageUrl: "/images/characters/op-bepo.jpg",
    description: "Navegante de los Piratas de Heart, oso mink",
    haki: false,
    recompensa: 500,
    origen: "Zou",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Bear",
    role: "supporting",
    abilities: ["Navegación", "Fuerza mink", "Electro"]
  },
  {
    id: "op-bigmom",
    name: "Charlotte Linlin",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Big Mom",
    imageUrl: "/images/characters/op-bigmom.jpg",
    description: "Emperatriz del Mar, matriarca familia Charlotte",
    haki: true,
    recompensa: 4388000000,
    origen: "Elbaf",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Soru Soru no Mi",
    element: "Soul",
    role: "main",
    abilities: ["Control de almas", "Fuerza monstruosa", "Homies"]
  },
  {
    id: "op-blackbeard",
    name: "Blackbeard",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-blackbeard.jpg",
    description: "Emperador del Mar, único con dos frutas del diablo",
    haki: true,
    recompensa: 3996000000,
    origen: "Isla Banaro",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Yami Yami no Mi; Gura Gura no Mi",
    element: "Darkness",
    role: "main",
    abilities: ["Oscuridad", "Terremotos", "Absorción de poderes"]
  },
  {
    id: "op-blueno",
    name: "Blueno",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-blueno.jpg",
    description: "Agente CP-9, usuario de la fruta puerta",
    haki: false,
    recompensa: null,
    origen: "Water 7",
    tipo_haki: [],
    fruta_diablo: "Doa Doa no Mi",
    element: "Door",
    role: "supporting",
    abilities: ["Creación de puertas", "Rokushiki", "Espionaje"]
  },
  {
    id: "op-bonclay",
    name: "Bon Clay",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Newkama Land",
    imageUrl: "/images/characters/op-bonclay.jpg",
    description: "Ex-agente Baroque Works, actual reina de Newkama Land",
    haki: false,
    recompensa: 32000000,
    origen: "Momoiro",
    tipo_haki: [],
    fruta_diablo: "Mane Mane no Mi",
    element: "Clone",
    role: "supporting",
    abilities: ["Transformación", "Okama Kenpo", "Amistad"]
  },
  {
    id: "op-bonney",
    name: "Jewelry Bonney",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bonney Pirates",
    imageUrl: "/images/characters/op-bonney.jpg",
    description: "Capitana de la Peor Generación, relacionada con Kuma",
    haki: false,
    recompensa: 320000000,
    origen: "Reino Sorbet",
    tipo_haki: [],
    fruta_diablo: "Toshi Toshi no Mi",
    element: "Age",
    role: "supporting",
    abilities: ["Manipulación de edad", "Liderazgo pirata", "Supervivencia"]
  },
  {
    id: "op-brogy",
    name: "Brogy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Giant Warrior Pirates",
    imageUrl: "/images/characters/op-brogy.jpg",
    description: "Gigante guerrero de Elbaf, co-capitán junto a Dorry",
    haki: false,
    recompensa: 100000000,
    origen: "Elbaf",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Giant",
    role: "supporting",
    abilities: ["Fuerza gigante", "Hacha de guerra", "Honor guerrero"]
  },
  {
    id: "op-brook",
    name: "Brook",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-brook.jpg",
    description: "Músico de los Piratas del Sombrero de Paja",
    haki: false,
    recompensa: 383000000,
    origen: "West Blue",
    tipo_haki: [],
    fruta_diablo: "Yomi Yomi no Mi",
    element: "Soul",
    role: "main",
    abilities: ["Música", "Esgrima", "Proyección astral"]
  },
  {
    id: "op-brulee",
    name: "Charlotte Brûlée",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Big Mom",
    imageUrl: "/images/characters/op-brulee.jpg",
    description: "8va hija de Big Mom, usuaria de espejos",
    haki: false,
    recompensa: null,
    origen: "Totto Land",
    tipo_haki: [],
    fruta_diablo: "Mira Mira no Mi",
    element: "Mirror",
    role: "supporting",
    abilities: ["Mundo espejo", "Teletransporte", "Reflejo"]
  },
  {
    id: "op-buffalo",
    name: "Buffalo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-buffalo.jpg",
    description: "Subordinado de Doflamingo, usuario de rotación",
    haki: false,
    recompensa: 32000000,
    origen: "North Blue",
    tipo_haki: [],
    fruta_diablo: "Guru Guru no Mi",
    element: "Rotation",
    role: "supporting",
    abilities: ["Rotación", "Vuelo", "Transporte"]
  },
  {
    id: "op-buggy",
    name: "Buggy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Cross Guild",
    imageUrl: "/images/characters/op-buggy.jpg",
    description: "Emperador del Mar, líder de Cross Guild",
    haki: false,
    recompensa: 3189000000,
    origen: "Grand Line",
    tipo_haki: [],
    fruta_diablo: "Bara Bara no Mi",
    element: "Fragment",
    role: "supporting",
    abilities: ["Fragmentación", "Liderazgo", "Suerte"]
  },
  {
    id: "op-burgess",
    name: "Jesus Burgess",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-burgess.jpg",
    description: "Primer comandante de Kurohige, luchador",
    haki: true,
    recompensa: 20000000,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Riki Riki no Mi",
    element: "Strength",
    role: "supporting",
    abilities: ["Fuerza aumentada", "Lucha libre", "Resistencia"]
  },
  {
    id: "op-caesar",
    name: "Caesar Clown",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Independiente",
    imageUrl: "/images/characters/op-caesar.jpg",
    description: "Científico loco, ex-socio de Vegapunk",
    haki: false,
    recompensa: 300000000,
    origen: "South Blue",
    tipo_haki: [],
    fruta_diablo: "Gasu Gasu no Mi",
    element: "Gas",
    role: "supporting",
    abilities: ["Control de gases", "Ciencia", "Armas químicas"]
  },
  {
    id: "op-caribou",
    name: "Caribou",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Caribou Pirates",
    imageUrl: "/images/characters/op-caribou.jpg",
    description: "Pirata novato, usuario del pantano",
    haki: false,
    recompensa: 210000000,
    origen: "East Blue",
    tipo_haki: [],
    fruta_diablo: "Numa Numa no Mi",
    element: "Swamp",
    role: "supporting",
    abilities: ["Pantano", "Almacenamiento", "Emboscadas"]
  },
  {
    id: "op-carrot",
    name: "Carrot",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Mink Guardians",
    imageUrl: "/images/characters/op-carrot.jpg",
    description: "Guerrera mink de Zou, amiga de los Sombrero de Paja",
    haki: false,
    recompensa: null,
    origen: "Zou",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Electric",
    role: "supporting",
    abilities: ["Electro", "Sulong", "Agilidad"]
  },
  {
    id: "op-cavendish",
    name: "Cavendish",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Beautiful Pirates",
    imageUrl: "/images/characters/op-cavendish.jpg",
    description: "Príncipe pirata, personalidad dual con Hakuba",
    haki: true,
    recompensa: 330000000,
    origen: "Reino Rommel",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Hakuba", "Carisma"]
  },
  {
    id: "op-charlos",
    name: "Saint Charlos",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Dragon Celestial",
    imageUrl: "/images/characters/op-charlos.jpg",
    description: "Dragón Celestial arrogante y despreciable",
    haki: false,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Noble",
    role: "supporting",
    abilities: ["Privilegios", "Arrogancia", "Protección mundial"]
  },
  {
    id: "op-chinjao",
    name: "Don Chinjao",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Happo Navy",
    imageUrl: "/images/characters/op-chinjao.jpg",
    description: "Ex-líder de la Marina Happo, guerrero veterano",
    haki: true,
    recompensa: 542000000,
    origen: "Pais Kano",
    tipo_haki: ["Armamento", "Conquistador"],
    fruta_diablo: null,
    element: "Drill",
    role: "supporting",
    abilities: ["Cabeza taladro", "Haki del Conquistador", "Liderazgo"]
  },
  {
    id: "op-chopper",
    name: "Tony Tony Chopper",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-chopper.jpg",
    description: "Doctor de los Piratas del Sombrero de Paja",
    haki: false,
    recompensa: 1000,
    origen: "Drum Island",
    tipo_haki: [],
    fruta_diablo: "Hito Hito no Mi",
    element: "Medical",
    role: "main",
    abilities: ["Medicina", "Transformaciones", "Monster Point"]
  },
  {
    id: "op-cindry",
    name: "Victoria Cindry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-cindry.jpg",
    description: "Zombi sirviente de Hogback en Thriller Bark",
    haki: false,
    recompensa: null,
    origen: "Saint Poplar",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Zombie",
    role: "supporting",
    abilities: ["Fuerza zombi", "Servicio", "Resistencia"]
  },
  {
    id: "op-cobra",
    name: "Nefertari Cobra",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rey de Arabasta",
    imageUrl: "/images/characters/op-cobra.jpg",
    description: "Rey de Arabasta, padre de Vivi",
    haki: false,
    recompensa: null,
    origen: "Arabasta",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Royal",
    role: "supporting",
    abilities: ["Liderazgo real", "Diplomacia", "Historia antigua"]
  },
  {
    id: "op-corazon",
    name: "Donquixote Rosinante",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-corazon.jpg",
    description: "Hermano de Doflamingo, agente marino encubierto",
    haki: false,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: "Nagi Nagi no Mi",
    element: "Silent",
    role: "supporting",
    abilities: ["Silencio", "Infiltración", "Sacrificio"]
  },
  {
    id: "op-cracker",
    name: "Charlotte Cracker",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Big Mom",
    imageUrl: "/images/characters/op-cracker.jpg",
    description: "Comandante Dulce de Big Mom, usuario de galletas",
    haki: true,
    recompensa: 860000000,
    origen: "Totto Land",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Bisu Bisu no Mi",
    element: "Biscuit",
    role: "supporting",
    abilities: ["Soldados galleta", "Armadura", "Esgrima"]
  },
  {
    id: "op-crocodile",
    name: "Sir Crocodile",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Cross Guild",
    imageUrl: "/images/characters/op-crocodile.jpg",
    description: "Ex-Shichibukai, co-líder de Cross Guild",
    haki: false,
    recompensa: 1965000000,
    origen: "Arabasta",
    tipo_haki: [],
    fruta_diablo: "Suna Suna no Mi",
    element: "Sand",
    role: "supporting",
    abilities: ["Control de arena", "Deshidratación", "Estrategia"]
  },
  {
    id: "op-dadan",
    name: "Curly Dadan",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bandidos de la Montaña Dadan",
    imageUrl: "/images/characters/op-dadan.jpg",
    description: "Líder de los bandidos de montaña, cuidó a Luffy y Ace",
    haki: false,
    recompensa: null,
    origen: "Reino Goa",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Bandit",
    role: "supporting",
    abilities: ["Liderazgo bandidos", "Cuidado maternal", "Supervivencia"]
  },
  {
    id: "op-dalton",
    name: "Dalton",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino Sakura",
    imageUrl: "/images/characters/op-dalton.jpg",
    description: "Rey de Sakura, ex-guardia de Wapol",
    haki: true,
    recompensa: null,
    origen: "Drum Island",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Uma Uma no Mi modelo bisonte",
    element: "Bison",
    role: "supporting",
    abilities: ["Transformación bisonte", "Liderazgo", "Lealtad"]
  },
  {
    id: "op-denjiro",
    name: "Denjiro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-denjiro.jpg",
    description: "Uno de los Nueve Vainas Rojas, seguidor leal de Oden",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Lealtad", "Infiltración"]
  },
  {
    id: "op-dochiriluk",
    name: "Dr. Hiriluk",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Medico de Drum",
    imageUrl: "/images/characters/op-dochiriluk.jpg",
    description: "Doctor curandero, mentor de Chopper",
    haki: false,
    recompensa: null,
    origen: "Drum Island",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Medicina", "Inspiración", "Sacrificio"]
  },
  {
    id: "op-docq",
    name: "Doc Q",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-docq.jpg",
    description: "Doctor de los Piratas de Kurohige, usuario de enfermedades",
    haki: false,
    recompensa: 72000000,
    origen: "North Blue",
    tipo_haki: [],
    fruta_diablo: "Shiku Shiku no Mi",
    element: "Disease",
    role: "supporting",
    abilities: ["Enfermedades", "Medicina", "Destino"]
  },
  {
    id: "op-doflamingo",
    name: "Donquixote Doflamingo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-doflamingo.jpg",
    description: "Ex-Shichibukai, tirano de Dressrosa",
    haki: true,
    recompensa: 340000000,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Ito Ito no Mi",
    element: "String",
    role: "main",
    abilities: ["Control de hilos", "Haki del Conquistador", "Manipulación"]
  },
  {
    id: "op-dorry",
    name: "Dorry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Giant Warrior Pirates",
    imageUrl: "/images/characters/op-dorry.jpg",
    description: "Gigante guerrero de Elbaf, co-capitán junto a Brogy",
    haki: false,
    recompensa: 100000000,
    origen: "Elbaf",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Giant",
    role: "supporting",
    abilities: ["Fuerza gigante", "Espada gigante", "Honor guerrero"]
  },
  {
    id: "op-drake",
    name: "X Drake",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "SWORD",
    imageUrl: "/images/characters/op-drake.jpg",
    description: "Capitán de la Marina, agente encubierto SWORD",
    haki: true,
    recompensa: 222000000,
    origen: "North Blue",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Ryu Ryu no Mi modelo allosaurio",
    element: "Dinosaur",
    role: "supporting",
    abilities: ["Transformación dinosaurio", "Infiltración", "Combate"]
  },
  {
    id: "op-enel",
    name: "Enel",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Sacerdotes de Skypiea",
    imageUrl: "/images/characters/op-enel.jpg",
    description: "Ex-Dios de Skypiea, usuario del rayo",
    haki: true,
    recompensa: null,
    origen: "Birka",
    tipo_haki: ["Observacion"],
    fruta_diablo: "Goro Goro no Mi",
    element: "Lightning",
    role: "main",
    abilities: ["Control del rayo", "Mantra", "Arca Maxim"]
  },
  {
    id: "op-franky",
    name: "Franky",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-franky.jpg",
    description: "Carpintero de los Piratas del Sombrero de Paja",
    haki: false,
    recompensa: 394000000,
    origen: "Water 7",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Cyborg",
    role: "main",
    abilities: ["Tecnología cyborg", "Construcción naval", "Radical Beam"]
  },
  {
    id: "op-fujitora",
    name: "Fujitora",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-fujitora.jpg",
    description: "Almirante de la Marina, usuario de gravedad",
    haki: true,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Zushi Zushi no Mi",
    element: "Gravity",
    role: "supporting",
    abilities: ["Control gravedad", "Esgrima ciega", "Justicia"]
  },
  {
    id: "op-fukuro",
    name: "Fukuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-fukuro.jpg",
    description: "Agente CP-9, especialista en Rokushiki",
    haki: false,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Zipper",
    role: "supporting",
    abilities: ["Rokushiki", "Información", "Cremalleras"]
  },
  {
    id: "op-gaban",
    name: "Scopper Gaban",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Roger",
    imageUrl: "/images/characters/op-gaban.jpg",
    description: "Tercer miembro más fuerte de los Piratas de Roger",
    haki: true,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Axe",
    role: "supporting",
    abilities: ["Hachas duales", "Haki", "Lealtad Roger"]
  },
  {
    id: "op-gaimon",
    name: "Gaimon",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Independiente",
    imageUrl: "/images/characters/op-gaimon.jpg",
    description: "Hombre atrapado en cofre del tesoro",
    haki: false,
    recompensa: null,
    origen: "East Blue",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Chest",
    role: "supporting",
    abilities: ["Supervivencia", "Amistad animal", "Paciencia"]
  },
  {
    id: "op-garling",
    name: "Saint Garling",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Caballeros de Dios",
    imageUrl: "/images/characters/op-garling.jpg",
    description: "Líder de los Caballeros de Dios",
    haki: true,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Divine",
    role: "supporting",
    abilities: ["Poder divino", "Liderazgo", "Autoridad absoluta"]
  },
  {
    id: "op-garp",
    name: "Garp",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-garp.jpg",
    description: "Héroe de la Marina, abuelo de Luffy",
    haki: true,
    recompensa: null,
    origen: "Reino Goa",
    tipo_haki: ["Armamento", "Conquistador"],
    fruta_diablo: null,
    element: "Fist",
    role: "main",
    abilities: ["Galaxy Impact", "Haki del Conquistador", "Fuerza legendaria"]
  },
  {
    id: "op-hancock",
    name: "Boa Hancock",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Kuja Pirates",
    imageUrl: "/images/characters/op-hancock.jpg",
    description: "Emperatriz Pirata, ex-Shichibukai",
    haki: true,
    recompensa: 1659000000,
    origen: "Amazon Lily",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Mero Mero no Mi",
    element: "Love",
    role: "main",
    abilities: ["Petrificación", "Haki del Conquistador", "Belleza suprema"]
  },
  {
    id: "op-hatchan",
    name: "Hatchan",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Sun Pirates",
    imageUrl: "/images/characters/op-hatchan.jpg",
    description: "Hombre-pez pulpo, ex-oficial de Arlong",
    haki: false,
    recompensa: 8000000,
    origen: "Isla Gyojin",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Octopus",
    role: "supporting",
    abilities: ["Seis espadas", "Cocina", "Natación"]
  },
  {
    id: "op-hattor",
    name: "Hattori",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Paloma de Lucci",
    imageUrl: "/images/characters/op-hattor.jpg",
    description: "Paloma compañera de Rob Lucci",
    haki: false,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Bird",
    role: "supporting",
    abilities: ["Vuelo", "Compañerismo", "Mensajería"]
  },
  {
    id: "op-hawkin",
    name: "Basil Hawkins",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Hawkins Pirates",
    imageUrl: "/images/characters/op-hawkin.jpg",
    description: "Capitán de la Peor Generación, usuario del vudú",
    haki: true,
    recompensa: 320000000,
    origen: "North Blue",
    tipo_haki: ["Observacion"],
    fruta_diablo: "Wara Wara no Mi",
    element: "Voodoo",
    role: "supporting",
    abilities: ["Cartas del tarot", "Muñecos vudú", "Predicción"]
  },
  {
    id: "op-helmeppo",
    name: "Helmeppo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-helmeppo.jpg",
    description: "Teniente Comandante Marina, compañero de Koby",
    haki: true,
    recompensa: null,
    origen: "Shells Town",
    tipo_haki: ["Observacion"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Rokushiki", "Crecimiento personal"]
  },
  {
    id: "op-hiyori",
    name: "Kozuki Hiyori",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Familia Kozuki",
    imageUrl: "/images/characters/op-hiyori.jpg",
    description: "Hija de Oden, hermana de Momonosuke",
    haki: false,
    recompensa: null,
    origen: "Wano",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Music",
    role: "supporting",
    abilities: ["Música", "Nobleza", "Supervivencia"]
  },
  {
    id: "op-hodi",
    name: "Hody Jones",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "New Fish-Man Pirates",
    imageUrl: "/images/characters/op-hodi.jpg",
    description: "Capitán de los Nuevos Piratas Hombre-Pez",
    haki: false,
    recompensa: null,
    origen: "Isla Gyojin",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Shark",
    role: "supporting",
    abilities: ["Fuerza hombre-pez", "Energy Steroids", "Odio"]
  },
  {
    id: "op-hogback",
    name: "Dr. Hogback",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-hogback.jpg",
    description: "Doctor de Thriller Bark, especialista en zombis",
    haki: false,
    recompensa: null,
    origen: "West Blue",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Cirugía", "Creación zombis", "Medicina"]
  },
  {
    id: "op-iceburg",
    name: "Iceburg",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Galley-La Company",
    imageUrl: "/images/characters/op-iceburg.jpg",
    description: "Alcalde de Water 7, presidente de Galley-La",
    haki: false,
    recompensa: null,
    origen: "Water 7",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Builder",
    role: "supporting",
    abilities: ["Construcción naval", "Liderazgo", "Diplomacia"]
  },
  {
    id: "op-igaram",
    name: "Igaram",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Guardia Real Arabasta",
    imageUrl: "/images/characters/op-igaram.jpg",
    description: "Capitán de la Guardia Real de Arabasta",
    haki: false,
    recompensa: null,
    origen: "Arabasta",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Armas de fuego", "Lealtad real", "Infiltración"]
  },
  {
    id: "op-imu",
    name: "Im",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gobierno Mundial",
    imageUrl: "/images/characters/op-imu.jpg",
    description: "Gobernante secreto del mundo, figura suprema",
    haki: true,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Shadow",
    role: "main",
    abilities: ["Poder absoluto", "Control mundial", "Misterio"]
  },
  {
    id: "op-inuarashi",
    name: "Inuarashi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-inuarashi.jpg",
    description: "Duque del día en Zou, uno de los Nueve Vainas Rojas",
    haki: true,
    recompensa: null,
    origen: "Zou",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Dog",
    role: "supporting",
    abilities: ["Combate mink", "Electro", "Liderazgo"]
  },
  {
    id: "op-ivankov",
    name: "Emporio Ivankov",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Revolucionario",
    imageUrl: "/images/characters/op-ivankov.jpg",
    description: "Comandante del Ejército Revolucionario, Reina Milagro",
    haki: true,
    recompensa: null,
    origen: "Reino Kamabakka",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Horu Horu no Mi",
    element: "Hormone",
    role: "supporting",
    abilities: ["Control hormonal", "Death Wink", "Revolución"]
  },
  {
    id: "op-izo",
    name: "Izo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Barbablanca",
    imageUrl: "/images/characters/op-izo.jpg",
    description: "16° Comandante de División de Barbablanca",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Doble pistola", "Precisión", "Honor samurai"]
  },
  {
    id: "op-jabra",
    name: "Jabra",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-jabra.jpg",
    description: "Agente CP-9, usuario de transformación lobo",
    haki: true,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Inu Inu no Mi modelo lobo",
    element: "Wolf",
    role: "supporting",
    abilities: ["Transformación lobo", "Rokushiki", "Combate feroz"]
  },
  {
    id: "op-jinbei",
    name: "Jinbe",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-jinbe.jpg",
    description: "Timonel de los Piratas del Sombrero de Paja",
    haki: true,
    recompensa: 1100000000,
    origen: "Isla Gyojin",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Water",
    role: "main",
    abilities: ["Karate Gyojin", "Control del agua", "Sabiduría"]
  },
  {
    id: "op-jupeter",
    name: "Saint Jupeter",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-jupeter.jpg",
    description: "Miembro de los Cinco Ancianos",
    haki: true,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Poder mundial", "Autoridad", "Conocimiento ancestral"]
  },
  {
    id: "op-kaido",
    name: "Kaido",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de las Bestias",
    imageUrl: "/images/characters/op-kaido.jpg",
    description: "Rey de las Bestias, criatura más fuerte del mundo",
    haki: true,
    recompensa: 4611100000,
    origen: "Reino Vodka",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Uo Uo no Mi modelo Seiryu",
    element: "Dragon",
    role: "main",
    abilities: ["Dragón azul", "Fuerza indestructible", "Haki supremo"]
  },
  {
    id: "op-kaku",
    name: "Kaku",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-0",
    imageUrl: "/images/characters/op-kaku.jpg",
    description: "Agente CP-0, ex-carpintero de Water 7",
    haki: true,
    recompensa: null,
    origen: "Water 7",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Ushi Ushi no Mi modelo jirafa",
    element: "Giraffe",
    role: "supporting",
    abilities: ["Transformación jirafa", "Rokushiki", "Esgrima"]
  },
  {
    id: "op-kalifa",
    name: "Kalifa",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-kalifa.jpg",
    description: "Agente CP-9, ex-secretaria de Iceburg",
    haki: false,
    recompensa: null,
    origen: "Water 7",
    tipo_haki: [],
    fruta_diablo: "Awa Awa no Mi",
    element: "Soap",
    role: "supporting",
    abilities: ["Burbujas de jabón", "Rokushiki", "Infiltración"]
  },
  {
    id: "op-kanjuro",
    name: "Kurozumi Kanjuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Clan Kurozumi",
    imageUrl: "/images/characters/op-kanjuro.jpg",
    description: "Espía del Clan Kurozumi infiltrado en los Akazaya",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Fude Fude no Mi",
    element: "Paint",
    role: "supporting",
    abilities: ["Creaciones artísticas", "Traición", "Actuación"]
  },
  {
    id: "op-katakuri",
    name: "Charlotte Katakuri",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Big Mom",
    imageUrl: "/images/characters/op-katakuri.jpg",
    description: "Primer hijo de Big Mom, usuario de mochi",
    haki: true,
    recompensa: 1057000000,
    origen: "Totto Land",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Mochi Mochi no Mi",
    element: "Mochi",
    role: "main",
    abilities: ["Observación futuro", "Mochi", "Honor familiar"]
  },
  {
    id: "op-kaya",
    name: "Kaya",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Villa Syrup",
    imageUrl: "/images/characters/op-kaya.jpg",
    description: "Amiga de Usopp, heredera rica de Villa Syrup",
    haki: false,
    recompensa: null,
    origen: "Villa Syrup",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Medicina", "Gentileza", "Riqueza"]
  },
  {
    id: "op-kid",
    name: "Eustass Kid",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kid",
    imageUrl: "/images/characters/op-kid.jpg",
    description: "Capitán de la Peor Generación, usuario del magnetismo",
    haki: true,
    recompensa: 3000000000,
    origen: "South Blue",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Jiki Jiki no Mi",
    element: "Magnet",
    role: "main",
    abilities: ["Magnetismo", "Haki del Conquistador", "Ferocidad"]
  },
  {
    id: "op-kikunojo",
    name: "Kikunojo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-kikunojo.jpg",
    description: "Una de los Nueve Vainas Rojas, guerrera samurai",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima samurai", "Lealtad", "Elegancia"]
  },
  {
    id: "op-killer",
    name: "Killer",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kid",
    imageUrl: "/images/characters/op-killer.jpg",
    description: "Primer oficial de Kid, guerrero enmascarado",
    haki: true,
    recompensa: 600000000,
    origen: "South Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "SMILE fallida",
    element: "Blade",
    role: "supporting",
    abilities: ["Cuchillas giratorias", "Velocidad", "Lealtad a Kid"]
  },
  {
    id: "op-kinemon",
    name: "Kinemon",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-kinemon.jpg",
    description: "Líder de los Nueve Vainas Rojas",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Fuku Fuku no Mi",
    element: "Clothes",
    role: "supporting",
    abilities: ["Creación de ropa", "Liderazgo", "Lealtad Oden"]
  },
  {
    id: "op-king",
    name: "King",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de las Bestias",
    imageUrl: "/images/characters/op-king.jpg",
    description: "Mano derecha de Kaido, último superviviente Lunaria",
    haki: true,
    recompensa: 1390000000,
    origen: "Nacion Lunaria",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Ryu Ryu no Mi modelo pteranodon",
    element: "Fire",
    role: "supporting",
    abilities: ["Vuelo prehistórico", "Fuego racial", "Lealtad Kaido"]
  },
  {
    id: "op-kizaru",
    name: "Kizaru",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-kizaru.jpg",
    description: "Almirante Marina, usuario de la luz",
    haki: true,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Pika Pika no Mi",
    element: "Light",
    role: "supporting",
    abilities: ["Velocidad luz", "Láseres", "Justicia ambigua"]
  },
  {
    id: "op-koby",
    name: "Koby",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-koby.jpg",
    description: "Capitán Marina, primer amigo de Luffy",
    haki: true,
    recompensa: null,
    origen: "East Blue",
    tipo_haki: ["Observacion"],
    fruta_diablo: null,
    element: "Fist",
    role: "supporting",
    abilities: ["Rokushiki", "Crecimiento rápido", "Justicia"]
  },
  {
    id: "op-koza",
    name: "Koza",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Rebelde Arabasta",
    imageUrl: "/images/characters/op-koza.jpg",
    description: "Líder de la rebelión en Arabasta, amigo de Vivi",
    haki: false,
    recompensa: null,
    origen: "Arabasta",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Rebel",
    role: "supporting",
    abilities: ["Liderazgo rebelde", "Amistad", "Justicia"]
  },
  {
    id: "op-kuina",
    name: "Kuina",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Dojo Shimotsuki",
    imageUrl: "/images/characters/op-kuina.jpg",
    description: "Amiga de la infancia de Zoro, espadachín prodigio",
    haki: false,
    recompensa: null,
    origen: "Villa Shimotsuki",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima talentosa", "Determinación", "Inspiración"]
  },
  {
    id: "op-kuma",
    name: "Bartholomew Kuma",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Revolucionario",
    imageUrl: "/images/characters/op-kuma.jpg",
    description: "Ex-Shichibukai, cyborg revolucionario",
    haki: false,
    recompensa: 296000000,
    origen: "Reino Sorbet",
    tipo_haki: [],
    fruta_diablo: "Nikyu Nikyu no Mi",
    element: "Paw",
    role: "supporting",
    abilities: ["Repulsión", "Teletransporte", "Sacrificio"]
  },
  {
    id: "op-kureha",
    name: "Dr. Kureha",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino Sakura",
    imageUrl: "/images/characters/op-kureha.jpg",
    description: "Doctora de 140 años, mentora de Chopper",
    haki: false,
    recompensa: null,
    origen: "Drum Island",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Medicina suprema", "Longevidad", "Sabiduría"]
  },
  {
    id: "op-kuro",
    name: "Kuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Gato Negro",
    imageUrl: "/images/characters/op-kuro.jpg",
    description: "Ex-capitán pirata, estratega calculador",
    haki: false,
    recompensa: 16000000,
    origen: "Villa Syrup",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Claw",
    role: "supporting",
    abilities: ["Garras de gato", "Velocidad", "Estrategia fría"]
  },
  {
    id: "op-kyros",
    name: "Kyros",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Coliseo Corrida",
    imageUrl: "/images/characters/op-kyros.jpg",
    description: "Gladiador legendario, padre de Rebecca",
    haki: true,
    recompensa: null,
    origen: "Dressrosa",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima con una pierna", "Amor paternal", "Honor"]
  },
  {
    id: "op-lafitte",
    name: "Lafitte",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-lafitte.jpg",
    description: "Navegante de Kurohige, ex-sheriff corrompido",
    haki: true,
    recompensa: 42200000,
    origen: "West Blue",
    tipo_haki: ["Observacion"],
    fruta_diablo: "Desconocida",
    element: "Wings",
    role: "supporting",
    abilities: ["Vuelo", "Hipnosis", "Infiltración"]
  },
  {
    id: "op-law",
    name: "Trafalgar D. Water Law",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Heart",
    imageUrl: "/images/characters/op-law.jpg",
    description: "Cirujano de la Muerte, capitán de la Peor Generación",
    haki: true,
    recompensa: 3000000000,
    origen: "Flevance",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Ope Ope no Mi",
    element: "Surgery",
    role: "main",
    abilities: ["Room", "Cirugía espacial", "Estrategia médica"]
  },
  {
    id: "op-leo",
    name: "Leo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Tontatta Pirates",
    imageUrl: "/images/characters/op-leo.jpg",
    description: "Capitán de los Piratas Tontatta",
    haki: false,
    recompensa: null,
    origen: "Reino Tontatta",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Plant",
    role: "supporting",
    abilities: ["Costura natural", "Liderazgo enano", "Lealtad"]
  },
  {
    id: "op-lola",
    name: "Lola",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rolling Pirates",
    imageUrl: "/images/characters/op-lola.jpg",
    description: "Capitana pirata, hija de Big Mom",
    haki: false,
    recompensa: 24000000,
    origen: "Totto Land",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Warthog",
    role: "supporting",
    abilities: ["Propuestas", "Liderazgo pirata", "Resistencia familiar"]
  },
  {
    id: "op-lucci",
    name: "Rob Lucci",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-0",
    imageUrl: "/images/characters/op-lucci.jpg",
    description: "Agente CP-0 más fuerte, usuario leopardo",
    haki: true,
    recompensa: null,
    origen: "East Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Neko Neko no Mi modelo leopardo",
    element: "Leopard",
    role: "main",
    abilities: ["Transformación leopardo", "Rokushiki maestro", "Justicia oscura"]
  },
  {
    id: "op-luckyroux",
    name: "Lucky Roux",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Pelirrojo",
    imageUrl: "/images/characters/op-luckyroux.jpg",
    description: "Cocinero de los Piratas del Pelirrojo",
    haki: true,
    recompensa: null,
    origen: "East Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Velocidad sorprendente", "Cocina", "Disparo certero"]
  },
  {
    id: "op-luffy",
    name: "Luffy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-luffy.jpg",
    description: "Capitán de los Piratas del Sombrero de Paja, futuro Rey Pirata",
    haki: true,
    recompensa: 3000000000,
    origen: "Villa Foosha",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Hito Hito no Mi modelo Nika",
    element: "Rubber",
    role: "main",
    abilities: ["Gear 5", "Liberación", "Haki del Conquistador"]
  },
  {
    id: "op-magellan",
    name: "Magellan",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Impel Down",
    imageUrl: "/images/characters/op-magellan.jpg",
    description: "Director de Impel Down, usuario del veneno",
    haki: true,
    recompensa: null,
    origen: "Grand Line",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Doku Doku no Mi",
    element: "Poison",
    role: "supporting",
    abilities: ["Veneno letal", "Hidra venenosa", "Justicia carcelaria"]
  },
  {
    id: "op-makino",
    name: "Makino",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bar de Foosha",
    imageUrl: "/images/characters/op-makino.jpg",
    description: "Dueña del bar en Villa Foosha, figura maternal",
    haki: false,
    recompensa: null,
    origen: "Villa Foosha",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Care",
    role: "supporting",
    abilities: ["Cuidado maternal", "Cocina", "Bondad"]
  },
  {
    id: "op-mansherry",
    name: "Princess Mansherry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino Tontatta",
    imageUrl: "/images/characters/op-mansherry.jpg",
    description: "Princesa de los Tontatta, usuaria de curación",
    haki: false,
    recompensa: null,
    origen: "Dressrosa",
    tipo_haki: [],
    fruta_diablo: "Chiyu Chiyu no Mi",
    element: "Heal",
    role: "supporting",
    abilities: ["Curación milagrosa", "Liderazgo enano", "Compasión"]
  },
  {
    id: "op-marco",
    name: "Marco",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Barbablanca",
    imageUrl: "/images/characters/op-marco.jpg",
    description: "1er Comandante de Barbablanca, el Fénix",
    haki: true,
    recompensa: 1374000000,
    origen: "Aldea Sphinx",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Tori Tori no Mi modelo fenix",
    element: "Phoenix",
    role: "main",
    abilities: ["Regeneración", "Vuelo", "Llamas curativas"]
  },
  {
    id: "op-marcusmars",
    name: "Saint Marcus Mars",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-marcusmars.jpg",
    description: "Miembro de los Cinco Ancianos",
    haki: true,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Poder mundial", "Autoridad suprema", "Conocimiento oculto"]
  },
  {
    id: "op-merry",
    name: "Merry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Villa Syrup",
    imageUrl: "/images/characters/op-merry.jpg",
    description: "Mayordomo de Kaya en Villa Syrup",
    haki: false,
    recompensa: null,
    origen: "Villa Syrup",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Service",
    role: "supporting",
    abilities: ["Servicio leal", "Cuidado", "Administración"]
  },
  {
    id: "op-momonga",
    name: "Momonga",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-momonga.jpg",
    description: "Vicealmirante Marina, espadachín disciplinado",
    haki: true,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima marina", "Disciplina", "Liderazgo militar"]
  },
  {
    id: "op-momonosuke",
    name: "Kozuki Momonosuke",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Shogun de Wano",
    imageUrl: "/images/characters/op-momonosuke.jpg",
    description: "Shogun de Wano, hijo de Oden",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Uo Uo no Mi modelo Seiryu artificial",
    element: "Dragon",
    role: "supporting",
    abilities: ["Transformación dragón", "Liderazgo noble", "Voz de Todas las Cosas"]
  },
  {
    id: "op-monet",
    name: "Monet",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-monet.jpg",
    description: "Subordinada de Doflamingo, usuaria de nieve",
    haki: false,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: [],
    fruta_diablo: "Yuki Yuki no Mi",
    element: "Snow",
    role: "supporting",
    abilities: ["Control de nieve", "Vuelo", "Lealtad absoluta"]
  },
  {
    id: "op-morgans",
    name: "Big News Morgans",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "World Economic Journal",
    imageUrl: "/images/characters/op-morgans.jpg",
    description: "Emperador del Inframundo, rey de las noticias",
    haki: false,
    recompensa: null,
    origen: "Sky Island",
    tipo_haki: [],
    fruta_diablo: "Tori Tori no Mi modelo albatros",
    element: "News",
    role: "supporting",
    abilities: ["Periodismo mundial", "Vuelo", "Información"]
  },
  {
    id: "op-moria",
    name: "Gecko Moria",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark Pirates",
    imageUrl: "/images/characters/op-moria.jpg",
    description: "Ex-Shichibukai, señor de las sombras",
    haki: false,
    recompensa: 320000000,
    origen: "West Blue",
    tipo_haki: [],
    fruta_diablo: "Kage Kage no Mi",
    element: "Shadow",
    role: "supporting",
    abilities: ["Control de sombras", "Zombis", "Pesadillas"]
  },
  {
    id: "op-nami",
    name: "Nami",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-nami.jpg",
    description: "Navegante de los Piratas del Sombrero de Paja",
    haki: false,
    recompensa: 366000000,
    origen: "Cocoyasi",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Weather",
    role: "main",
    abilities: ["Climatact", "Navegación suprema", "Cartografía"]
  },
  {
    id: "op-neptune",
    name: "Neptune",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rey Isla Gyojin",
    imageUrl: "/images/characters/op-neptune.jpg",
    description: "Rey de la Isla Gyojin, padre de Shirahoshi",
    haki: true,
    recompensa: null,
    origen: "Isla Gyojin",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Water",
    role: "supporting",
    abilities: ["Karate Gyojin real", "Liderazgo", "Diplomacia"]
  },
  {
    id: "op-nojiko",
    name: "Nojiko",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Cocoyasi",
    imageUrl: "/images/characters/op-nojiko.jpg",
    description: "Hermana adoptiva de Nami",
    haki: false,
    recompensa: null,
    origen: "Cocoyasi",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Care",
    role: "supporting",
    abilities: ["Cuidado familiar", "Agricultura", "Apoyo emocional"]
  },
  {
    id: "op-nusjuro",
    name: "Saint Nusjuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-nusjuro.jpg",
    description: "Miembro de los Cinco Ancianos",
    haki: true,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Autoridad mundial", "Esgrima ancestral", "Poder oculto"]
  },
  {
    id: "op-oars",
    name: "Oars",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-oars.jpg",
    description: "Zombi gigante animado con la sombra de Luffy",
    haki: false,
    recompensa: null,
    origen: "Pais Antiguos Gigantes",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Giant",
    role: "supporting",
    abilities: ["Fuerza colosal", "Técnicas de Luffy", "Resistencia zombi"]
  },
  {
    id: "op-oden",
    name: "Kozuki Oden",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Roger",
    imageUrl: "/images/characters/op-oden.jpg",
    description: "Señor de Wano, espadachín legendario",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: null,
    element: "Sword",
    role: "main",
    abilities: ["Oden Nitoryu", "Voz de Todas las Cosas", "Liderazgo carismático"]
  },
  {
    id: "op-orochi",
    name: "Kurozumi Orochi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Shogun de Wano",
    imageUrl: "/images/characters/op-orochi.jpg",
    description: "Ex-Shogun corrupto de Wano",
    haki: false,
    recompensa: null,
    origen: "Wano",
    tipo_haki: [],
    fruta_diablo: "Hebi Hebi no Mi modelo Yamata no Orochi",
    element: "Snake",
    role: "supporting",
    abilities: ["Ocho cabezas", "Cobardía", "Manipulación"]
  },
  {
    id: "op-paulie",
    name: "Paulie",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Galley-La Company",
    imageUrl: "/images/characters/op-paulie.jpg",
    description: "Capataz de Galley-La Company",
    haki: false,
    recompensa: null,
    origen: "Water 7",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Rope",
    role: "supporting",
    abilities: ["Técnicas de cuerda", "Construcción naval", "Liderazgo obrero"]
  },
  {
    id: "op-pedro",
    name: "Pedro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Nox Pirates",
    imageUrl: "/images/characters/op-pedro.jpg",
    description: "Líder de los Nox Pirates, guerrero mink",
    haki: true,
    recompensa: 382000000,
    origen: "Zou",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Electric",
    role: "supporting",
    abilities: ["Espada electrificada", "Sacrificio", "Liderazgo mink"]
  },
  {
    id: "op-pekoms",
    name: "Pekoms",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Big Mom",
    imageUrl: "/images/characters/op-pekoms.jpg",
    description: "Combatiente de Big Mom, mink tortuga",
    haki: true,
    recompensa: 330000000,
    origen: "Zou",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Kame Kame no Mi",
    element: "Turtle",
    role: "supporting",
    abilities: ["Defensa de tortuga", "Electro mink", "Lealtad dividida"]
  },
  {
    id: "op-pell",
    name: "Pell",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Guardia Real Arabasta",
    imageUrl: "/images/characters/op-pell.jpg",
    description: "El Halcón, guardián de Arabasta",
    haki: false,
    recompensa: null,
    origen: "Arabasta",
    tipo_haki: [],
    fruta_diablo: "Tori Tori no Mi modelo halcon",
    element: "Falcon",
    role: "supporting",
    abilities: ["Vuelo halcón", "Lealtad real", "Sacrificio heroico"]
  },
  {
    id: "op-perona",
    name: "Perona",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-perona.jpg",
    description: "Princesa fantasma de Thriller Bark",
    haki: false,
    recompensa: null,
    origen: "Desconocido",
    tipo_haki: [],
    fruta_diablo: "Horo Horo no Mi",
    element: "Ghost",
    role: "supporting",
    abilities: ["Fantasmas negativos", "Proyección astral", "Pesimismo"]
  },
  {
    id: "op-raizo",
    name: "Raizo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-raizo.jpg",
    description: "Ninja de Wano, uno de los Nueve Vainas Rojas",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Maki Maki no Mi",
    element: "Scroll",
    role: "supporting",
    abilities: ["Jutsu ninja", "Pergaminos", "Lealtad samurai"]
  },
  {
    id: "op-rebecca",
    name: "Rebecca",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Familia Real Dressrosa",
    imageUrl: "/images/characters/op-rebecca.jpg",
    description: "Gladiadora de Dressrosa, princesa",
    haki: true,
    recompensa: null,
    origen: "Dressrosa",
    tipo_haki: ["Observacion"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima defensiva", "Velocidad", "Bondad real"]
  },
  {
    id: "op-reiju",
    name: "Vinsmoke Reiju",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Germa 66",
    imageUrl: "/images/characters/op-reiju.jpg",
    description: "Poison Pink, hermana de Sanji",
    haki: false,
    recompensa: null,
    origen: "Reino Germa",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Poison",
    role: "supporting",
    abilities: ["Inmunidad veneno", "Absorción toxinas", "Compasión oculta"]
  },
  {
    id: "op-riku",
    name: "Riku Doldo III",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rey de Dressrosa",
    imageUrl: "/images/characters/op-riku.jpg",
    description: "Rey legítimo de Dressrosa",
    haki: true,
    recompensa: null,
    origen: "Dressrosa",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima real", "Liderazgo noble", "Justicia"]
  },
  {
    id: "op-robin",
    name: "Nico Robin",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-robin.jpg",
    description: "Arqueóloga de los Piratas del Sombrero de Paja",
    haki: true,
    recompensa: 930000000,
    origen: "Ohara",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Hana Hana no Mi",
    element: "Flower",
    role: "main",
    abilities: ["Clonar extremidades", "Arqueología", "Poneglyphs"]
  },
  {
    id: "op-roger",
    name: "Roger",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Roger",
    imageUrl: "/images/characters/op-roger.jpg",
    description: "Rey de los Piratas, iniciador de la Gran Era",
    haki: true,
    recompensa: 5564800000,
    origen: "Loguetown",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: null,
    element: "Sword",
    role: "main",
    abilities: ["Voz de Todas las Cosas", "Haki supremo", "Liderazgo legendario"]
  },
  {
    id: "op-ryuma",
    name: "Ryuma",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Wano",
    imageUrl: "/images/characters/op-ryuma.jpg",
    description: "Samurai legendario de Wano",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima legendaria", "Honor samurai", "Protección nacional"]
  },
  {
    id: "op-sabo",
    name: "Sabo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Revolucionario",
    imageUrl: "/images/characters/op-sabo.jpg",
    description: "Jefe de Estado Mayor del Ejército Revolucionario",
    haki: true,
    recompensa: 602000000,
    origen: "Reino Goa",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Mera Mera no Mi",
    element: "Fire",
    role: "main",
    abilities: ["Puño de fuego", "Garra de dragón", "Revolución"]
  },
  {
    id: "op-sakazuki",
    name: "Sakazuki",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-sakazuki.jpg",
    description: "Almirante de la Flota, usuario del magma",
    haki: true,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Magu Magu no Mi",
    element: "Magma",
    role: "main",
    abilities: ["Magma devastador", "Justicia absoluta", "Puño de meteoro"]
  },
  {
    id: "op-saldeath",
    name: "Saldeath",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Impel Down",
    imageUrl: "/images/characters/op-saldeath.jpg",
    description: "Guardián de Impel Down",
    haki: false,
    recompensa: null,
    origen: "Impel Down",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Fire",
    role: "supporting",
    abilities: ["Lanzallamas", "Guardia carcelaria", "Disciplina"]
  },
  {
    id: "op-sanji",
    name: "Vinsmoke Sanji",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-sanji.jpg",
    description: "Cocinero de los Piratas del Sombrero de Paja",
    haki: true,
    recompensa: 1032000000,
    origen: "North Blue",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Fire",
    role: "main",
    abilities: ["Pierna del diablo", "Cocina suprema", "Caballerosidad"]
  },
  {
    id: "op-saturn",
    name: "Saint Saturn",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-saturn.jpg",
    description: "Miembro de los Cinco Ancianos",
    haki: true,
    recompensa: null,
    origen: "Mary Geoise",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Autoridad suprema", "Poder oculto", "Control mundial"]
  },
  {
    id: "op-sengoku",
    name: "Sengoku",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-sengoku.jpg",
    description: "Ex-Almirante de la Flota, el Buda",
    haki: true,
    recompensa: null,
    origen: "Grand Line",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Hito Hito no Mi modelo daibutsu",
    element: "Buddha",
    role: "supporting",
    abilities: ["Forma Buda dorada", "Ondas de choque", "Estrategia militar"]
  },
  {
    id: "op-shanks",
    name: "Akagami no Shanks",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Pelirrojo",
    imageUrl: "/images/characters/op-shanks.jpg",
    description: "Emperador del Mar, mentor de Luffy",
    haki: true,
    recompensa: 4048900000,
    origen: "West Blue",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: null,
    element: "Sword",
    role: "main",
    abilities: ["Haki supremo", "Esgrima divina", "Liderazgo carismático"]
  },
  {
    id: "op-shiki",
    name: "Shiki",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Golden Lion Pirates",
    imageUrl: "/images/characters/op-shiki.jpg",
    description: "León Dorado, rival de Roger",
    haki: true,
    recompensa: null,
    origen: "Grand Line",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Fuwa Fuwa no Mi",
    element: "Float",
    role: "supporting",
    abilities: ["Levitación", "Espadas en piernas", "Ambición imperial"]
  },
  {
    id: "op-shimotsuki",
    name: "Shimotsuki Yasuie",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Wano",
    imageUrl: "/images/characters/op-shimotsuki.jpg",
    description: "Ex-Daimyo de Hakumai, padre adoptivo de Toko",
    haki: false,
    recompensa: null,
    origen: "Wano",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Smile",
    role: "supporting",
    abilities: ["Sacrificio noble", "Liderazgo paternal", "Resistencia"]
  },
  {
    id: "op-shiryu",
    name: "Shiryu",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Kurohige",
    imageUrl: "/images/characters/op-shiryu.jpg",
    description: "Ex-jefe guardián de Impel Down",
    haki: true,
    recompensa: null,
    origen: "Impel Down",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Suke Suke no Mi",
    element: "Invisible",
    role: "supporting",
    abilities: ["Invisibilidad", "Esgrima letal", "Sed de sangre"]
  },
  {
    id: "op-shuraiya",
    name: "Shuraiya Bascùd",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marine",
    imageUrl: "/images/characters/op-shuraiya.jpg",
    description: "Cazarrecompensas marino",
    haki: false,
    recompensa: null,
    origen: "East Blue",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Puntería experta", "Caza recompensas", "Justicia personal"]
  },
  {
    id: "op-smoothie",
    name: "Charlotte Smoothie",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Big Mom",
    imageUrl: "/images/characters/op-smoothie.jpg",
    description: "Comandante de Big Mom, usuaria del exprimido",
    haki: true,
    recompensa: 932000000,
    origen: "Totto Land",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Shibo Shibo no Mi",
    element: "Juice",
    role: "supporting",
    abilities: ["Exprimir líquidos", "Gigantismo", "Espada gigante"]
  },
  {
    id: "op-spandam",
    name: "Spandam",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-0",
    imageUrl: "/images/characters/op-spandam.jpg",
    description: "Ex-jefe de CP9, ahora en CP-0",
    haki: false,
    recompensa: null,
    origen: "Grand Line",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Espada elefante", "Comando", "Cobardía"]
  },
  {
    id: "op-squard",
    name: "Squard",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Maelstrom Spider Pirates",
    imageUrl: "/images/characters/op-squard.jpg",
    description: "Capitán aliado de Barbablanca",
    haki: true,
    recompensa: 210000000,
    origen: "New World",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Espada gigante", "Traición", "Lealtad recuperada"]
  },
  {
    id: "op-sugar",
    name: "Sugar",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-sugar.jpg",
    description: "Ejecutiva de Doflamingo, usuaria de juguetes",
    haki: false,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: [],
    fruta_diablo: "Hobi Hobi no Mi",
    element: "Toy",
    role: "supporting",
    abilities: ["Conversión juguete", "Borrado memoria", "Juventud eterna"]
  },
  {
    id: "op-toko",
    name: "Toko",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Wano",
    imageUrl: "/images/characters/op-toko.jpg",
    description: "Niña de Wano, hija adoptiva de Yasuie",
    haki: false,
    recompensa: null,
    origen: "Wano",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Smile",
    role: "supporting",
    abilities: ["Risa constante", "Inocencia", "Amor filial"]
  },
  {
    id: "op-trebol",
    name: "Trebol",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-trebol.jpg",
    description: "Ejecutivo de Doflamingo, usuario pegajoso",
    haki: true,
    recompensa: 99000000,
    origen: "North Blue",
    tipo_haki: ["Armamento"],
    fruta_diablo: "Beta Beta no Mi",
    element: "Sticky",
    role: "supporting",
    abilities: ["Sustancia pegajosa", "Explosiones", "Manipulación"]
  },
  {
    id: "op-tsuru",
    name: "Tsuru",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-tsuru.jpg",
    description: "Vicealmirante veterana, usuaria del lavado",
    haki: true,
    recompensa: null,
    origen: "Grand Line",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: "Woshu Woshu no Mi",
    element: "Wash",
    role: "supporting",
    abilities: ["Lavar y tender", "Estrategia", "Veteranía"]
  },
  {
    id: "op-usopp",
    name: "Usopp",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Sombrero de Paja",
    imageUrl: "/images/characters/op-usopp.jpg",
    description: "Francotirador de los Piratas del Sombrero de Paja",
    haki: true,
    recompensa: 500000000,
    origen: "Villa Syrup",
    tipo_haki: ["Observacion"],
    fruta_diablo: null,
    element: "Plant",
    role: "main",
    abilities: ["Francotirador supremo", "Pop Greens", "Valentía gradual"]
  },
  {
    id: "op-vander",
    name: "Vander Decken IX",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Flying Pirates",
    imageUrl: "/images/characters/op-vander.jpg",
    description: "Capitán usuario del objetivo",
    haki: false,
    recompensa: null,
    origen: "Isla Gyojin",
    tipo_haki: [],
    fruta_diablo: "Mato Mato no Mi",
    element: "Target",
    role: "supporting",
    abilities: ["Objetivo automático", "Persecución", "Obsesión"]
  },
  {
    id: "op-vergo",
    name: "Vergo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-vergo.jpg",
    description: "Ex-vicealmirante, agente de Doflamingo",
    haki: true,
    recompensa: null,
    origen: "North Blue",
    tipo_haki: ["Armamento"],
    fruta_diablo: null,
    element: "Bamboo",
    role: "supporting",
    abilities: ["Haki de cuerpo completo", "Combate bambú", "Doble agente"]
  },
  {
    id: "op-vivi",
    name: "Nefertari Vivi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Familia Real Arabasta",
    imageUrl: "/images/characters/op-vivi.jpg",
    description: "Princesa de Arabasta, ex-tripulante honoraria",
    haki: false,
    recompensa: null,
    origen: "Arabasta",
    tipo_haki: [],
    fruta_diablo: null,
    element: "Peace",
    role: "main",
    abilities: ["Diplomacia", "Liderazgo real", "Amistad eterna"]
  },
  {
    id: "op-whitebeard",
    name: "Edward Newgate",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas de Barbablanca",
    imageUrl: "/images/characters/op-whitebeard.jpg",
    description: "Barbablanca, el Hombre Más Fuerte del Mundo",
    haki: true,
    recompensa: 5046000000,
    origen: "Isla Sphinx",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Gura Gura no Mi",
    element: "Earthquake",
    role: "main",
    abilities: ["Terremotos", "Haki supremo", "Paternidad pirata"]
  },
  {
    id: "op-yamato",
    name: "Yamato",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Samurai de Wano",
    imageUrl: "/images/characters/op-yamato.jpg",
    description: "Hijo de Kaido, admirador de Oden",
    haki: true,
    recompensa: null,
    origen: "Wano",
    tipo_haki: ["Armamento", "Observacion", "Conquistador"],
    fruta_diablo: "Inu Inu no Mi modelo okuchi no makami",
    element: "Wolf",
    role: "main",
    abilities: ["Transformación lobo", "Hielo sagrado", "Voluntad de Oden"]
  },
  {
    id: "op-yassop",
    name: "Yassop",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratas del Pelirrojo",
    imageUrl: "/images/characters/op-yassop.jpg",
    description: "Francotirador de Shanks, padre de Usopp",
    haki: true,
    recompensa: null,
    origen: "Villa Syrup",
    tipo_haki: ["Armamento", "Observacion"],
    fruta_diablo: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Puntería perfecta", "Francotirador", "Abandono paternal"]
  }
];

// FUNCIONES DE BÚSQUEDA ACTUALIZADAS
export const getCharactersByBirthPlace = (place: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.origen.includes(place));
};

export const getCharactersByCrew = (crew: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => 
    char.crew.toLowerCase().includes(crew.toLowerCase())
  );
};

export const getCharactersByBountyRange = (min: number, max: number): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => {
    if (char.recompensa === null) return false;
    return char.recompensa >= min && char.recompensa <= max;
  });
};

export const getCharactersWithHaki = (hakiType?: string): AnimeCharacter[] => {
  if (!hakiType) return ANIME_CHARACTERS.filter(char => char.haki);
  
  return ANIME_CHARACTERS.filter(char => 
    char.tipo_haki.some(type => type.toLowerCase().includes(hakiType.toLowerCase()))
  );
};

export const getCharactersWithDevilFruit = (): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.fruta_diablo !== null);
};

export const getCharactersByRole = (role: 'main' | 'supporting'): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.role === role);
};

export const getRandomCharacter = (): AnimeCharacter => {
  const randomIndex = Math.floor(Math.random() * ANIME_CHARACTERS.length);
  return ANIME_CHARACTERS[randomIndex];
};

export const getCharacterByName = (name: string): AnimeCharacter | undefined => {
  return ANIME_CHARACTERS.find(char => 
    char.name.toLowerCase().includes(name.toLowerCase()) ||
    char.nameEnglish?.toLowerCase().includes(name.toLowerCase())
  );
};

export const getCharactersByAnime = (animeId: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.animeId === animeId);
};

export const getOnePieceCharacters = (): AnimeCharacter[] => {
  return getCharactersByAnime('onepiece');
};

// Helper functions for filtering by new characteristics
export const getCharactersByRecompensa = (minRecompensa?: number, maxRecompensa?: number): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => {
    if (character.recompensa === null) return false;
    if (minRecompensa && character.recompensa < minRecompensa) return false;
    if (maxRecompensa && character.recompensa > maxRecompensa) return false;
    return true;
  });
};

export const getCharactersByOrigen = (origen: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    character.origen.toLowerCase().includes(origen.toLowerCase())
  );
};

export const getCharactersByTipoHaki = (tipoHaki: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    character.tipo_haki.some(haki => 
      haki.toLowerCase().includes(tipoHaki.toLowerCase())
    )
  );
};

export const getCharactersByFrutaDiablo = (frutaName?: string): AnimeCharacter[] => {
  if (frutaName) {
    return ANIME_CHARACTERS.filter(character => 
      character.fruta_diablo && 
      character.fruta_diablo.toLowerCase().includes(frutaName.toLowerCase())
    );
  }
  // Return characters with any devil fruit
  return ANIME_CHARACTERS.filter(character => 
    character.fruta_diablo && character.fruta_diablo !== null
  );
};

export const getCharactersWithoutFrutaDiablo = (): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    character.fruta_diablo === null
  );
};

export const getCharactersByHakiTypes = (hakiTypes: string[]): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    hakiTypes.every(haki => 
      character.tipo_haki.some(charHaki => 
        charHaki.toLowerCase().includes(haki.toLowerCase())
      )
    )
  );
};

export const getTopRecompensas = (limit: number = 10): AnimeCharacter[] => {
  return ANIME_CHARACTERS
    .filter(character => character.recompensa !== null)
    .sort((a, b) => (b.recompensa || 0) - (a.recompensa || 0))
    .slice(0, limit);
};

export const getCharacterStats = () => {
  const total = ANIME_CHARACTERS.length;
  const withRecompensa = ANIME_CHARACTERS.filter(c => c.recompensa !== null).length;
  const withFrutaDiablo = ANIME_CHARACTERS.filter(c => c.fruta_diablo !== null).length;
  const withHaki = ANIME_CHARACTERS.filter(c => c.tipo_haki.length > 0).length;
  const conquerorHaki = ANIME_CHARACTERS.filter(c => 
    c.tipo_haki.some(h => h.toLowerCase().includes('conquistador'))
  ).length;

  return {
    total,
    withRecompensa,
    withFrutaDiablo,
    withHaki,
    conquerorHaki,
    withoutRecompensa: total - withRecompensa,
    withoutFrutaDiablo: total - withFrutaDiablo,
    withoutHaki: total - withHaki
  };
};
