// One Piece Character Database - Updated with 164 characters

export interface AnimeCharacter {
  id: string;
  name: string;
  nameEnglish?: string;
  anime: string;
  animeId: string;
  crew: string;
  imageUrl: string;
  description: string;
  
  // GAME CATEGORIES - Boolean (YES/NO)
  haki: boolean;                    // Has haki?
  
  // GAME CATEGORIES - Specific Values (specific answers)
  bounty: number | null;            // Bounty (null = no bounty)
  origin: string;                   // Place of origin
  hakiTypes: string[];              // Types of haki possessed
  devilFruit: string | null;        // Devil fruit name (null = no devil fruit)
  
  // DISPLAY-ONLY (only for character pages, NOT for games)
  element?: string;
  role?: 'main' | 'supporting';
  abilities?: string[];
}

export const ANIME_CHARACTERS: AnimeCharacter[] = [
  {
    id: "op-absalom",
    name: "Absalom",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark Pirates",
    imageUrl: "/images/characters/op-absalom.webp",
    description: "Zombi general de Thriller Bark with the invisibility devil fruit",
    haki: false,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: [],
    devilFruit: "Clear-Clear Fruit",
    element: "Invisible",
    role: "supporting",
    abilities: ["Invisibility", "Enhanced strength", "Zombie leadership"]
  },
  {
    id: "op-ace",
    name: "Ace",
    anime: "One Piece", 
    animeId: "onepiece",
    crew: "Pirates Barbablanca",
    imageUrl: "/images/characters/op-ace.webp",
    description: "Comandante de la 2ª División de Barbablanca, hermano de Luffy",
    haki: true,
    bounty: 550000000,
    origin: "Baterilla",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Flame-Flame Fruit",
    element: "Fire",
    role: "main",
    abilities: ["Puño de Fuego", "Haki del Conquistador", "Comandante División"]
  },
  {
    id: "op-akainu",
    name: "Akainu",
    anime: "One Piece",
    animeId: "onepiece", 
    crew: "Marina",
    imageUrl: "/images/characters/op-akainu.webp",
    description: "Almirante de la Flota de la Marina, usuario de magma",
    haki: true,
    bounty: null,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Magma-Magma Fruit",
    element: "Magma",
    role: "supporting",
    abilities: ["Puño de Magma", "Justicia Absoluta", "Liderazgo Marina"]
  },
  {
    id: "op-alvida",
    name: "Alvida",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Buggy's Delivery", 
    imageUrl: "/images/characters/op-alvida.webp",
    description: "Capitana pirata, primera enemiga de Luffy",
    haki: false,
    bounty: 5000000,
    origin: "East Blue",
    hakiTypes: [],
    devilFruit: "Sube Sube no Mi",
    element: "Smooth",
    role: "supporting", 
    abilities: ["Piel resbaladiza", "Fuerza bruta", "Liderazgo pirata"]
  },
  {
    id: "op-aokiji",
    name: "Aokiji",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-aokiji.webp", 
    description: "Ex-Almirante Marina, ahora afiliado a Kurohige",
    haki: true,
    bounty: null,
    origin: "South Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Ice-Ice Fruit",
    element: "Ice",
    role: "supporting",
    abilities: ["Ice Age", "Justicia Perezosa", "Fuerza Almirante"]
  },
  {
    id: "op-apoo",
    name: "Apoo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "On Air Pirates",
    imageUrl: "/images/characters/op-apoo.webp",
    description: "Captain of the On Air Pirates, member of the Worst Generation",
    haki: false,
    bounty: 350000000,
    origin: "Grand Line",
    hakiTypes: [],
    devilFruit: "Oto Oto no Mi",
    element: "Sound",
    role: "supporting",
    abilities: ["Ataques sónicos", "Music", "Liderazgo pirata"]
  },
  {
    id: "op-arlong",
    name: "Arlong",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Arlong Pirates",
    imageUrl: "/images/characters/op-arlong.webp",
    description: "Capitán hombre-pez, tirano de Cocoyasi",
    haki: false,
    bounty: 20000000,
    origin: "Fish-Man Island",
    hakiTypes: [],
    devilFruit: null,
    element: "Water",
    role: "supporting",
    abilities: ["Fuerza hombre-pez", "Dientes de sierra", "Armas dentales"]
  },
  {
    id: "op-augur",
    name: "Van Augur",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-augur.webp",
    description: "Francotirador de los Pirates Kurohige",
    haki: true,
    bounty: 64000000,
    origin: "Desconocido",
    hakiTypes: ["Observation"],
    devilFruit: "Wapu Wapu no Mi",
    element: "Gun",
    role: "supporting",
    abilities: ["Extreme sniping", "Teleportation", "Advanced observation"]
  },
  {
    id: "op-bellamy",
    name: "Bellamy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bellamy Pirates",
    imageUrl: "/images/characters/op-bellamy.webp",
    description: "Capitán Pirates Bellamy, seguidor de Doflamingo",
    haki: false,
    bounty: 195000000,
    origin: "North Blue",
    hakiTypes: [],
    devilFruit: "Bane Bane no Mi",
    element: "Spring",
    role: "supporting",
    abilities: ["Salto de resorte", "Impacto elástico", "Liderazgo pirata"]
  },
  {
    id: "op-bellemere",
    name: "Bell-mère",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-bellemere.webp",
    description: "Ex-marina, madre adoptiva de Nami y Nojiko",
    haki: false,
    bounty: null,
    origin: "Cocoyasi Village",
    hakiTypes: [],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Entrenamiento militar", "Cultivo", "Amor maternal"]
  },
  {
    id: "op-ben",
    name: "Ben Beckman",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Pelirrojo",
    imageUrl: "/images/characters/op-ben.webp",
    description: "Primer oficial de Shanks, intelectual de alto nivel",
    haki: true,
    bounty: null,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Strategy", "Armament", "Leadership"]
  },
  {
    id: "op-bepo",
    name: "Bepo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Heart",
    imageUrl: "/images/characters/op-bepo.webp",
    description: "Navegante de los Pirates Heart, oso mink",
    haki: false,
    bounty: 500,
    origin: "Zou",
    hakiTypes: [],
    devilFruit: null,
    element: "Bear",
    role: "supporting",
    abilities: ["Navigation", "Fuerza mink", "Electro"]
  },
  {
    id: "op-bigmom",
    name: "Big Mom",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-bigmom.webp",
    description: "Emperatriz del Mar, matriarca familia Charlotte",
    haki: true,
    bounty: 4388000000,
    origin: "Elbaf",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Soru Soru no Mi",
    element: "Soul",
    role: "main",
    abilities: ["Control de almas", "Fuerza monstruosa", "Homies"]
  },
  {
    id: "op-blackbeard",
    name: "Blackbeard",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-blackbeard.webp",
    description: "Emperador del Mar, único con dos frutas del diablo",
    haki: true,
    bounty: 3996000000,
    origin: "Isla Banaro",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Yami Yami no Mi; Gura Gura no Mi",
    element: "Darkness",
    role: "main",
    abilities: ["Oscuridad", "Terremotos", "Absorción de poderes"]
  },
  {
    id: "op-blueno",
    name: "Blueno",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-blueno.webp",
    description: "Agente CP-9, usuario de la fruta puerta",
    haki: false,
    bounty: null,
    origin: "Water 7",
    hakiTypes: [],
    devilFruit: "Door-Door Fruit",
    element: "Door",
    role: "supporting",
    abilities: ["Creación de puertas", "Rokushiki", "Espionaje"]
  },
  {
    id: "op-bonclay",
    name: "Bon Clay",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Newkama Land",
    imageUrl: "/images/characters/op-bonclay.webp",
    description: "Ex-agente Baroque Works, actual reina de Newkama Land",
    haki: false,
    bounty: 32000000,
    origin: "Momoiro",
    hakiTypes: [],
    devilFruit: "Clone-Clone Fruit",
    element: "Clone",
    role: "supporting",
    abilities: ["Transformation", "Okama Kenpo", "Amistad"]
  },
  {
    id: "op-bonney",
    name: "Jewelry Bonney",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bonney Pirates",
    imageUrl: "/images/characters/op-bonney.webp",
    description: "Capitana de la Peor Generación, relacionada con Kuma",
    haki: false,
    bounty: 320000000,
    origin: "Reino Sorbet",
    hakiTypes: [],
    devilFruit: "Toshi Toshi no Mi",
    element: "Age",
    role: "supporting",
    abilities: ["Manipulación de edad", "Liderazgo pirata", "Supervivencia"]
  },
  {
    id: "op-brogy",
    name: "Brogy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Giant Warrior Pirates",
    imageUrl: "/images/characters/op-brogy.webp",
    description: "Gigante guerrero de Elbaf, co-capitán junto a Dorry",
    haki: false,
    bounty: 100000000,
    origin: "Elbaf",
    hakiTypes: [],
    devilFruit: null,
    element: "Giant",
    role: "supporting",
    abilities: ["Fuerza gigante", "Hacha de guerra", "Honor guerrero"]
  },
  {
    id: "op-brook",
    name: "Brook",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-brook.webp",
    description: "Músico de los Piratesl Sombrero de Paja",
    haki: false,
    bounty: 383000000,
    origin: "West Blue",
    hakiTypes: [],
    devilFruit: "Revive-Revive Fruit",
    element: "Soul",
    role: "main",
    abilities: ["Music", "Esgrima", "Proyección astral"]
  },
  {
    id: "op-brulee",
    name: "Brûlée",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-brulee.webp",
    description: "8va hija de Big Mom, usuaria de espejos",
    haki: false,
    bounty: null,
    origin: "Totto Land",
    hakiTypes: [],
    devilFruit: "Mirror-Mirror Fruit",
    element: "Mirror",
    role: "supporting",
    abilities: ["Mundo espejo", "Teletransporte", "Reflejo"]
  },
  {
    id: "op-buffalo",
    name: "Buffalo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-buffalo.webp",
    description: "Subordinado de Doflamingo, usuario de rotación",
    haki: false,
    bounty: 32000000,
    origin: "North Blue",
    hakiTypes: [],
    devilFruit: "Spin-Spin Fruit",
    element: "Rotation",
    role: "supporting",
    abilities: ["Rotación", "Vuelo", "Transporte"]
  },
  {
    id: "op-buggy",
    name: "Buggy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Cross Guild",
    imageUrl: "/images/characters/op-buggy.webp",
    description: "Emperador del Mar, líder de Cross Guild",
    haki: false,
    bounty: 3189000000,
    origin: "Grand Line",
    hakiTypes: [],
    devilFruit: "Chop-Chop Fruit",
    element: "Fragment",
    role: "supporting",
    abilities: ["Fragmentación", "Leadership", "Suerte"]
  },
  {
    id: "op-burgess",
    name: "Jesus Burgess",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-burgess.webp",
    description: "Primer comandante de Kurohige, luchador",
    haki: true,
    bounty: 20000000,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Riki Riki no Mi",
    element: "Strength",
    role: "supporting",
    abilities: ["Enhanced strength", "Lucha libre", "Endurance"]
  },
  {
    id: "op-caesar",
    name: "Caesar Clown",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Independiente",
    imageUrl: "/images/characters/op-caesar.webp",
    description: "Científico loco, ex-socio de Vegapunk",
    haki: false,
    bounty: 300000000,
    origin: "South Blue",
    hakiTypes: [],
    devilFruit: "Gas-Gas Fruit",
    element: "Gas",
    role: "supporting",
    abilities: ["Control de gases", "Ciencia", "Armas químicas"]
  },
  {
    id: "op-caribou",
    name: "Caribou",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Caribou Pirates",
    imageUrl: "/images/characters/op-caribou.webp",
    description: "Pirata novato, usuario del pantano",
    haki: false,
    bounty: 210000000,
    origin: "East Blue",
    hakiTypes: [],
    devilFruit: "Numa Numa no Mi",
    element: "Swamp",
    role: "supporting",
    abilities: ["Pantano", "Almacenamiento", "Emboscadas"]
  },
  {
    id: "op-carrot",
    name: "Carrot",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Mink Guardians",
    imageUrl: "/images/characters/op-carrot.webp",
    description: "Guerrera mink de Zou, amiga de los Sombrero de Paja",
    haki: false,
    bounty: null,
    origin: "Zou",
    hakiTypes: [],
    devilFruit: null,
    element: "Electric",
    role: "supporting",
    abilities: ["Electro", "Sulong", "Agilidad"]
  },
  {
    id: "op-cavendish",
    name: "Cavendish",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Beautiful Pirates",
    imageUrl: "/images/characters/op-cavendish.webp",
    description: "Príncipe pirata, personalidad dual con Hakuba",
    haki: true,
    bounty: 330000000,
    origin: "Reino Rommel",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Hakuba", "Carisma"]
  },
  {
    id: "op-charlos",
    name: "Saint Charlos",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Dragon Celestial Dragon Dragon",
    imageUrl: "/images/characters/op-charlos.webp",
    description: "Dragón Celestial Dragon Dragon arrogante y despreciable",
    haki: false,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: null,
    element: "Noble",
    role: "supporting",
    abilities: ["Privilegios", "Arrogancia", "Protección mundial"]
  },
  {
    id: "op-chinjao",
    name: "Don Chinjao",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Happo Navy",
    imageUrl: "/images/characters/op-chinjao.webp",
    description: "Ex-líder de la Marina Happo, guerrero veterano",
    haki: true,
    bounty: 542000000,
    origin: "Pais Kano",
    hakiTypes: ["Armament", "Conqueror"],
    devilFruit: null,
    element: "Drill",
    role: "supporting",
    abilities: ["Cabeza taladro", "Haki del Conquistador", "Leadership"]
  },
  {
    id: "op-chopper",
    name: "Chopper",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-chopper.webp",
    description: "Doctor de los Piratesl Sombrero de Paja",
    haki: false,
    bounty: 1000,
    origin: "Drum Kingdom",
    hakiTypes: [],
    devilFruit: "Human-Human Fruit",
    element: "Medical",
    role: "main",
    abilities: ["Medicine", "Transformaciones", "Monster Point"]
  },
  {
    id: "op-cindry",
    name: "Cindry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-cindry.webp",
    description: "Zombi sirviente de Hogback en Thriller Bark",
    haki: false,
    bounty: null,
    origin: "Saint Poplar",
    hakiTypes: [],
    devilFruit: null,
    element: "Zombie",
    role: "supporting",
    abilities: ["Zombie strength", "Service", "Endurance"]
  },
  {
    id: "op-cobra",
    name: "Cobra",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "King of Arabasta",
    imageUrl: "/images/characters/op-cobra.webp",
    description: "King of Arabasta, Vivi's father",
    haki: false,
    bounty: null,
    origin: "Arabasta",
    hakiTypes: [],
    devilFruit: null,
    element: "Royal",
    role: "supporting",
    abilities: ["Liderazgo real", "Diplomacia", "Historia antigua"]
  },
  {
    id: "op-corazon",
    name: "Donquixote Rosinante",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-corazon.webp",
    description: "Hermano de Doflamingo, agente marino encubierto",
    haki: false,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: "Nagi Nagi no Mi",
    element: "Silent",
    role: "supporting",
    abilities: ["Silencio", "Infiltración", "Sacrificio"]
  },
  {
    id: "op-cracker",
    name: "Charlotte Cracker",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-cracker.webp",
    description: "Comandante Dulce de Big Mom, usuario de galletas",
    haki: true,
    bounty: 860000000,
    origin: "Totto Land",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Biscuit-Biscuit Fruit",
    element: "Biscuit",
    role: "supporting",
    abilities: ["Soldados galleta", "Armament", "Esgrima"]
  },
  {
    id: "op-crocodile",
    name: "Sir Crocodile",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Cross Guild",
    imageUrl: "/images/characters/op-crocodile.webp",
    description: "Ex-Warlord, co-líder de Cross Guild",
    haki: false,
    bounty: 1965000000,
    origin: "Arabasta",
    hakiTypes: [],
    devilFruit: "Sand-Sand Fruit",
    element: "Sand",
    role: "supporting",
    abilities: ["Control de arena", "Deshidratación", "Strategy"]
  },
  {
    id: "op-dadan",
    name: "Curly Dadan",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bandidos de la Montaña Dadan",
    imageUrl: "/images/characters/op-dadan.webp",
    description: "Líder de los bandidos de montaña, cuidó a Luffy y Ace",
    haki: false,
    bounty: null,
    origin: "Reino Goa",
    hakiTypes: [],
    devilFruit: null,
    element: "Bandit",
    role: "supporting",
    abilities: ["Liderazgo bandidos", "Cuidado maternal", "Supervivencia"]
  },
  {
    id: "op-dalton",
    name: "Dalton",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Sakura Kingdom",
    imageUrl: "/images/characters/op-dalton.webp",
    description: "King of Sakura, former guard of Wapol",
    haki: true,
    bounty: null,
    origin: "Drum Kingdom",
    hakiTypes: ["Armament"],
    devilFruit: "Uma Uma no Mi modelo bisonte",
    element: "Bison",
    role: "supporting",
    abilities: ["Transformación bisonte", "Leadership", "Lealtad"]
  },
  {
    id: "op-denjiro",
    name: "Denjiro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-denjiro.webp",
    description: "Uno de los Nueve Vainas Rojas, seguidor leal de Oden",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Lealtad", "Infiltración"]
  },
  {
    id: "op-dochiriluk",
    name: "Dr. Hiriluk",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Medico de Drum",
    imageUrl: "/images/characters/op-dochiriluk.webp",
    description: "Doctor curandero, mentor de Chopper",
    haki: false,
    bounty: null,
    origin: "Drum Kingdom",
    hakiTypes: [],
    devilFruit: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Medicine", "Inspiración", "Sacrificio"]
  },
  {
    id: "op-docq",
    name: "Doc Q",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-docq.webp",
    description: "Doctor de los Pirates Kurohige, usuario de enfermedades",
    haki: false,
    bounty: 72000000,
    origin: "North Blue",
    hakiTypes: [],
    devilFruit: "Shiku Shiku no Mi",
    element: "Disease",
    role: "supporting",
    abilities: ["Enfermedades", "Medicine", "Destino"]
  },
  {
    id: "op-doflamingo",
    name: "Donquixote Doflamingo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-doflamingo.webp",
    description: "Ex-Warlord, tirano de Dressrosa",
    haki: true,
    bounty: 340000000,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "String-String Fruit",
    element: "String",
    role: "main",
    abilities: ["Control de hilos", "Haki del Conquistador", "Manipulación"]
  },
  {
    id: "op-dorry",
    name: "Dorry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Giant Warrior Pirates",
    imageUrl: "/images/characters/op-dorry.webp",
    description: "Gigante guerrero de Elbaf, co-capitán junto a Brogy",
    haki: false,
    bounty: 100000000,
    origin: "Elbaf",
    hakiTypes: [],
    devilFruit: null,
    element: "Giant",
    role: "supporting",
    abilities: ["Fuerza gigante", "Espada gigante", "Honor guerrero"]
  },
  {
    id: "op-drake",
    name: "X Drake",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "SWORD",
    imageUrl: "/images/characters/op-drake.webp",
    description: "Capitán de la Marina, agente encubierto SWORD",
    haki: true,
    bounty: 222000000,
    origin: "North Blue",
    hakiTypes: ["Armament"],
    devilFruit: "Ryu Ryu no Mi modelo allosaurio",
    element: "Dinosaur",
    role: "supporting",
    abilities: ["Transformación dinosaurio", "Infiltración", "Combate"]
  },
  {
    id: "op-enel",
    name: "Enel",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Sacerdotes de Skypiea",
    imageUrl: "/images/characters/op-enel.webp",
    description: "Ex-Dios de Skypiea, usuario del rayo",
    haki: true,
    bounty: null,
    origin: "Birka",
    hakiTypes: ["Observation"],
    devilFruit: "Goro Goro no Mi",
    element: "Lightning",
    role: "main",
    abilities: ["Control del rayo", "Mantra", "Arca Maxim"]
  },
  {
    id: "op-franky",
    name: "Franky",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-franky.webp",
    description: "Carpintero de los Piratesl Sombrero de Paja",
    haki: false,
    bounty: 394000000,
    origin: "Water 7",
    hakiTypes: [],
    devilFruit: null,
    element: "Cyborg",
    role: "main",
    abilities: ["Tecnología cyborg", "Construcción naval", "Radical Beam"]
  },
  {
    id: "op-fujitora",
    name: "Fujitora",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-fujitora.webp",
    description: "Marine Admiral, usuario de gravedad",
    haki: true,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Press-Press Fruit",
    element: "Gravity",
    role: "supporting",
    abilities: ["Control gravedad", "Esgrima ciega", "Justicia"]
  },
  {
    id: "op-fukuro",
    name: "Fukuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-fukuro.webp",
    description: "Agente CP-9, especialista en Rokushiki",
    haki: false,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: [],
    devilFruit: null,
    element: "Zipper",
    role: "supporting",
    abilities: ["Rokushiki", "Información", "Cremalleras"]
  },
  {
    id: "op-gaban",
    name: "Scopper Gaban",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Roger",
    imageUrl: "/images/characters/op-gaban.webp",
    description: "Tercer miembro más fuerte de los Pirates Roger",
    haki: true,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Axe",
    role: "supporting",
    abilities: ["Hachas duales", "Haki", "Lealtad Roger"]
  },
  {
    id: "op-gaimon",
    name: "Gaimon",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Independiente",
    imageUrl: "/images/characters/op-gaimon.webp",
    description: "Hombre atrapado en cofre del tesoro",
    haki: false,
    bounty: null,
    origin: "East Blue",
    hakiTypes: [],
    devilFruit: null,
    element: "Chest",
    role: "supporting",
    abilities: ["Supervivencia", "Amistad animal", "Paciencia"]
  },
  {
    id: "op-garling",
    name: "Saint Garling",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Caballeros de Dios",
    imageUrl: "/images/characters/op-garling.webp",
    description: "Líder de los Caballeros de Dios",
    haki: true,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: null,
    element: "Divine",
    role: "supporting",
    abilities: ["Poder divino", "Leadership", "Autoridad absoluta"]
  },
  {
    id: "op-garp",
    name: "Garp",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-garp.webp",
    description: "Héroe de la Marina, abuelo de Luffy",
    haki: true,
    bounty: null,
    origin: "Reino Goa",
    hakiTypes: ["Armament", "Conqueror"],
    devilFruit: null,
    element: "Fist",
    role: "main",
    abilities: ["Galaxy Impact", "Haki del Conquistador", "Fuerza legendaria"]
  },
  {
    id: "op-hancock",
    name: "Boa Hancock",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Kuja Pirates",
    imageUrl: "/images/characters/op-hancock.webp",
    description: "Emperatriz Pirata, ex-Warlord",
    haki: true,
    bounty: 1659000000,
    origin: "Amazon Lily",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Mero Mero no Mi",
    element: "Love",
    role: "main",
    abilities: ["Petrificación", "Haki del Conquistador", "Belleza suprema"]
  },
  {
    id: "op-hatchan",
    name: "Hatchan",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Sun Pirates",
    imageUrl: "/images/characters/op-hatchan.webp",
    description: "Hombre-pez pulpo, ex-oficial de Arlong",
    haki: false,
    bounty: 8000000,
    origin: "Fish-Man Island",
    hakiTypes: [],
    devilFruit: null,
    element: "Octopus",
    role: "supporting",
    abilities: ["Seis espadas", "Cooking", "Natación"]
  },
  {
    id: "op-hattor",
    name: "Hattori",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Paloma de Lucci",
    imageUrl: "/images/characters/op-hattor.webp",
    description: "Paloma compañera de Rob Lucci",
    haki: false,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: [],
    devilFruit: null,
    element: "Bird",
    role: "supporting",
    abilities: ["Vuelo", "Compañerismo", "Mensajería"]
  },
  {
    id: "op-hawkin",
    name: "Basil Hawkins",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Hawkins Pirates",
    imageUrl: "/images/characters/op-hawkin.webp",
    description: "Capitán de la Peor Generación, usuario del vudú",
    haki: true,
    bounty: 320000000,
    origin: "North Blue",
    hakiTypes: ["Observation"],
    devilFruit: "Wara Wara no Mi",
    element: "Voodoo",
    role: "supporting",
    abilities: ["Cartas del tarot", "Muñecos vudú", "Predicción"]
  },
  {
    id: "op-helmeppo",
    name: "Helmeppo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-helmeppo.webp",
    description: "Teniente Comandante Marina, compañero de Koby",
    haki: true,
    bounty: null,
    origin: "Shells Town",
    hakiTypes: ["Observation"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Rokushiki", "Crecimiento personal"]
  },
  {
    id: "op-hiyori",
    name: "Kozuki Hiyori",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Familia Kozuki",
    imageUrl: "/images/characters/op-hiyori.webp",
    description: "Hija de Oden, hermana de Momonosuke",
    haki: false,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: [],
    devilFruit: null,
    element: "Music",
    role: "supporting",
    abilities: ["Music", "Nobleza", "Supervivencia"]
  },
  {
    id: "op-hodi",
    name: "Hody Jones",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "New Fish-Man Pirates",
    imageUrl: "/images/characters/op-hodi.webp",
    description: "Captain of the Nuevos Piratas Hombre-Pez",
    haki: false,
    bounty: null,
    origin: "Fish-Man Island",
    hakiTypes: [],
    devilFruit: null,
    element: "Shark",
    role: "supporting",
    abilities: ["Fuerza hombre-pez", "Energy Steroids", "Odio"]
  },
  {
    id: "op-hogback",
    name: "Dr. Hogback",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-hogback.webp",
    description: "Doctor de Thriller Bark, especialista en zombis",
    haki: false,
    bounty: null,
    origin: "West Blue",
    hakiTypes: [],
    devilFruit: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Cirugía", "Creación zombis", "Medicine"]
  },
  {
    id: "op-iceburg",
    name: "Iceburg",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Galley-La Company",
    imageUrl: "/images/characters/op-iceburg.webp",
    description: "Alcalde de Water 7, presidente de Galley-La",
    haki: false,
    bounty: null,
    origin: "Water 7",
    hakiTypes: [],
    devilFruit: null,
    element: "Builder",
    role: "supporting",
    abilities: ["Construcción naval", "Leadership", "Diplomacia"]
  },
  {
    id: "op-igaram",
    name: "Igaram",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Guardia Real Arabasta",
    imageUrl: "/images/characters/op-igaram.webp",
    description: "Capitán de la Guardia Real de Arabasta",
    haki: false,
    bounty: null,
    origin: "Arabasta",
    hakiTypes: [],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Armas de fuego", "Lealtad real", "Infiltración"]
  },
  {
    id: "op-imu",
    name: "Im",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gobierno Mundial",
    imageUrl: "/images/characters/op-imu.webp",
    description: "Gobernante secreto del mundo, figura suprema",
    haki: true,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: [],
    devilFruit: null,
    element: "Shadow",
    role: "main",
    abilities: ["Poder absoluto", "Control mundial", "Misterio"]
  },
  {
    id: "op-inuarashi",
    name: "Inuarashi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-inuarashi.webp",
    description: "Duque del día en Zou, uno de los Nueve Vainas Rojas",
    haki: true,
    bounty: null,
    origin: "Zou",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Dog",
    role: "supporting",
    abilities: ["Combate mink", "Electro", "Leadership"]
  },
  {
    id: "op-ivankov",
    name: "Emporio Ivankov",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Revolutionary",
    imageUrl: "/images/characters/op-ivankov.webp",
    description: "Comandante del Ejército Revolutionary, Reina Milagro",
    haki: true,
    bounty: null,
    origin: "Reino Kamabakka",
    hakiTypes: ["Armament"],
    devilFruit: "Hormone-Hormone Fruit",
    element: "Hormone",
    role: "supporting",
    abilities: ["Control hormonal", "Death Wink", "Revolución"]
  },
  {
    id: "op-izo",
    name: "Izo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Barbablanca",
    imageUrl: "/images/characters/op-izo.webp",
    description: "16° Comandante de División de Barbablanca",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Doble pistola", "Precisión", "Honor samurai"]
  },
  {
    id: "op-jabra",
    name: "Jabra",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-jabra.webp",
    description: "Agente CP-9, usuario de transformación lobo",
    haki: true,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: ["Armament"],
    devilFruit: "Inu Inu no Mi modelo lobo",
    element: "Wolf",
    role: "supporting",
    abilities: ["Transformación lobo", "Rokushiki", "Combate feroz"]
  },
  {
    id: "op-jinbei",
    name: "Jinbe",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-jinbei.webp",
    description: "Timonel de los Piratesl Sombrero de Paja",
    haki: true,
    bounty: 1100000000,
    origin: "Fish-Man Island",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Water",
    role: "main",
    abilities: ["Fish-Man Karate", "Water control", "Sabiduría"]
  },
  {
    id: "op-jupeter",
    name: "Saint Jupeter",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-jupeter.webp",
    description: "Member of the Cinco Ancianos",
    haki: true,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Poder mundial", "Autoridad", "Conocimiento ancestral"]
  },
  {
    id: "op-kaido",
    name: "Kaido",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates las Bestias",
    imageUrl: "/images/characters/op-kaido.webp",
    description: "Rey de las Bestias, criatura más fuerte del mundo",
    haki: true,
    bounty: 4611100000,
    origin: "Reino Vodka",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Uo Uo no Mi modelo Seiryu",
    element: "Dragon",
    role: "main",
    abilities: ["Dragón azul", "Fuerza indestructible", "Haki supremo"]
  },
  {
    id: "op-kaku",
    name: "Kaku",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-0",
    imageUrl: "/images/characters/op-kaku.webp",
    description: "Agente CP-0, ex-carpintero de Water 7",
    haki: true,
    bounty: null,
    origin: "Water 7",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Ushi Ushi no Mi modelo jirafa",
    element: "Giraffe",
    role: "supporting",
    abilities: ["Transformación jirafa", "Rokushiki", "Esgrima"]
  },
  {
    id: "op-kalifa",
    name: "Kalifa",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-9",
    imageUrl: "/images/characters/op-kalifa.webp",
    description: "Agente CP-9, ex-secretaria de Iceburg",
    haki: false,
    bounty: null,
    origin: "Water 7",
    hakiTypes: [],
    devilFruit: "Bubble-Bubble Fruit",
    element: "Soap",
    role: "supporting",
    abilities: ["Burbujas de jabón", "Rokushiki", "Infiltración"]
  },
  {
    id: "op-kanjuro",
    name: "Kurozumi Kanjuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Clan Kurozumi",
    imageUrl: "/images/characters/op-kanjuro.webp",
    description: "Espía del Clan Kurozumi infiltrado en los Akazaya",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament"],
    devilFruit: "Fude Fude no Mi",
    element: "Paint",
    role: "supporting",
    abilities: ["Creaciones artísticas", "Traición", "Actuación"]
  },
  {
    id: "op-katakuri",
    name: "Charlotte Katakuri",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-katakuri.webp",
    description: "Primer hijo de Big Mom, usuario de mochi",
    haki: true,
    bounty: 1057000000,
    origin: "Totto Land",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Mochi-Mochi Fruit",
    element: "Mochi",
    role: "main",
    abilities: ["Observación futuro", "Mochi", "Honor familiar"]
  },
  {
    id: "op-kaya",
    name: "Kaya",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Villa Syrup",
    imageUrl: "/images/characters/op-kaya.webp",
    description: "Amiga de Usopp, heredera rica de Villa Syrup",
    haki: false,
    bounty: null,
    origin: "Villa Syrup",
    hakiTypes: [],
    devilFruit: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Medicine", "Gentileza", "Riqueza"]
  },
  {
    id: "op-kid",
    name: "Eustass Kid",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kid",
    imageUrl: "/images/characters/op-kid.webp",
    description: "Capitán de la Peor Generación, usuario del magnetismo",
    haki: true,
    bounty: 3000000000,
    origin: "South Blue",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Jiki Jiki no Mi",
    element: "Magnet",
    role: "main",
    abilities: ["Magnetismo", "Haki del Conquistador", "Ferocidad"]
  },
  {
    id: "op-kikunojo",
    name: "Kikunojo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-kikunojo.webp",
    description: "Una de los Nueve Vainas Rojas, guerrera samurai",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima samurai", "Lealtad", "Elegancia"]
  },
  {
    id: "op-killer",
    name: "Killer",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kid",
    imageUrl: "/images/characters/op-killer.webp",
    description: "Primer oficial de Kid, guerrero enmascarado",
    haki: true,
    bounty: 600000000,
    origin: "South Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "SMILE fallida",
    element: "Blade",
    role: "supporting",
    abilities: ["Cuchillas giratorias", "Speed", "Lealtad a Kid"]
  },
  {
    id: "op-kinemon",
    name: "Kinemon",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-kinemon.webp",
    description: "Líder de los Nueve Vainas Rojas",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Garb-Garb Fruit",
    element: "Clothes",
    role: "supporting",
    abilities: ["Creación de ropa", "Leadership", "Lealtad Oden"]
  },
  {
    id: "op-king",
    name: "King",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates las Bestias",
    imageUrl: "/images/characters/op-king.webp",
    description: "Mano derecha de Kaido, último superviviente Lunaria",
    haki: true,
    bounty: 1390000000,
    origin: "Nacion Lunaria",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Ryu Ryu no Mi modelo pteranodon",
    element: "Fire",
    role: "supporting",
    abilities: ["Vuelo prehistórico", "Fuego racial", "Lealtad Kaido"]
  },
  {
    id: "op-kizaru",
    name: "Kizaru",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-kizaru.webp",
    description: "Almirante Marina, usuario de la luz",
    haki: true,
    bounty: null,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Glint-Glint Fruit",
    element: "Light",
    role: "supporting",
    abilities: ["Velocidad luz", "Láseres", "Justicia ambigua"]
  },
  {
    id: "op-koby",
    name: "Koby",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-koby.webp",
    description: "Capitán Marina, primer amigo de Luffy",
    haki: true,
    bounty: null,
    origin: "East Blue",
    hakiTypes: ["Observation"],
    devilFruit: null,
    element: "Fist",
    role: "supporting",
    abilities: ["Rokushiki", "Crecimiento rápido", "Justicia"]
  },
  {
    id: "op-koza",
    name: "Koza",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Rebelde Arabasta",
    imageUrl: "/images/characters/op-koza.webp",
    description: "Líder de la rebelión en Arabasta, amigo de Vivi",
    haki: false,
    bounty: null,
    origin: "Arabasta",
    hakiTypes: [],
    devilFruit: null,
    element: "Rebel",
    role: "supporting",
    abilities: ["Liderazgo rebelde", "Amistad", "Justicia"]
  },
  {
    id: "op-kuina",
    name: "Kuina",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Dojo Shimotsuki",
    imageUrl: "/images/characters/op-kuina.webp",
    description: "Amiga de la infancia de Zoro, espadachín prodigio",
    haki: false,
    bounty: null,
    origin: "Villa Shimotsuki",
    hakiTypes: [],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima talentosa", "Determinación", "Inspiración"]
  },
  {
    id: "op-kuma",
    name: "Bartholomew Kuma",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Revolutionary",
    imageUrl: "/images/characters/op-kuma.webp",
    description: "Ex-Warlord, cyborg revolucionario",
    haki: false,
    bounty: 296000000,
    origin: "Reino Sorbet",
    hakiTypes: [],
    devilFruit: "Paw-Paw Fruit",
    element: "Paw",
    role: "supporting",
    abilities: ["Repulsión", "Teletransporte", "Sacrificio"]
  },
  {
    id: "op-kureha",
    name: "Dr. Kureha",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino Sakura",
    imageUrl: "/images/characters/op-kureha.webp",
    description: "Doctora de 140 años, mentora de Chopper",
    haki: false,
    bounty: null,
    origin: "Drum Kingdom",
    hakiTypes: [],
    devilFruit: null,
    element: "Medical",
    role: "supporting",
    abilities: ["Medicina suprema", "Longevidad", "Sabiduría"]
  },
  {
    id: "op-kuro",
    name: "Kuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Gato Negro",
    imageUrl: "/images/characters/op-kuro.webp",
    description: "Ex-capitán pirata, estratega calculador",
    haki: false,
    bounty: 16000000,
    origin: "Villa Syrup",
    hakiTypes: [],
    devilFruit: null,
    element: "Claw",
    role: "supporting",
    abilities: ["Garras de gato", "Speed", "Estrategia fría"]
  },
  {
    id: "op-kyros",
    name: "Kyros",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Coliseo Corrida",
    imageUrl: "/images/characters/op-kyros.webp",
    description: "Gladiador legendario, padre de Rebecca",
    haki: true,
    bounty: null,
    origin: "Dressrosa",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima con una pierna", "Amor paternal", "Honor"]
  },
  {
    id: "op-lafitte",
    name: "Lafitte",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-lafitte.webp",
    description: "Navegante de Kurohige, ex-sheriff corrompido",
    haki: true,
    bounty: 42200000,
    origin: "West Blue",
    hakiTypes: ["Observation"],
    devilFruit: "Desconocida",
    element: "Wings",
    role: "supporting",
    abilities: ["Vuelo", "Hipnosis", "Infiltración"]
  },
  {
    id: "op-law",
    name: "Law",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Heart",
    imageUrl: "/images/characters/op-law.webp",
    description: "Cirujano de la Muerte, capitán de la Peor Generación",
    haki: true,
    bounty: 3000000000,
    origin: "Flevance",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Op-Op Fruit",
    element: "Surgery",
    role: "main",
    abilities: ["Room", "Cirugía espacial", "Estrategia médica"]
  },
  {
    id: "op-leo",
    name: "Leo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Tontatta Pirates",
    imageUrl: "/images/characters/op-leo.webp",
    description: "Captain of the Piratas Tontatta",
    haki: false,
    bounty: null,
    origin: "Reino Tontatta",
    hakiTypes: [],
    devilFruit: null,
    element: "Plant",
    role: "supporting",
    abilities: ["Costura natural", "Liderazgo enano", "Lealtad"]
  },
  {
    id: "op-lola",
    name: "Lola",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rolling Pirates",
    imageUrl: "/images/characters/op-lola.webp",
    description: "Capitana pirata, hija de Big Mom",
    haki: false,
    bounty: 24000000,
    origin: "Totto Land",
    hakiTypes: [],
    devilFruit: null,
    element: "Warthog",
    role: "supporting",
    abilities: ["Propuestas", "Liderazgo pirata", "Resistencia familiar"]
  },
  {
    id: "op-lucci",
    name: "Rob Lucci",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-0",
    imageUrl: "/images/characters/op-lucci.webp",
    description: "Agente CP-0 más fuerte, usuario leopardo",
    haki: true,
    bounty: null,
    origin: "East Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Neko Neko no Mi modelo leopardo",
    element: "Leopard",
    role: "main",
    abilities: ["Transformación leopardo", "Rokushiki maestro", "Justicia oscura"]
  },
  {
    id: "op-luckyroux",
    name: "Lucky Roux",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Pelirrojo",
    imageUrl: "/images/characters/op-luckyroux.webp",
    description: "Cocinero de los Piratesl Pelirrojo",
    haki: true,
    bounty: null,
    origin: "East Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Velocidad sorprendente", "Cooking", "Disparo certero"]
  },
  {
    id: "op-luffy",
    name: "Luffy",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-luffy.webp",
    description: "Captain of the Piratesl Sombrero de Paja, futuro Rey Pirata",
    haki: true,
    bounty: 3000000000,
    origin: "Villa Foosha",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Hito Hito no Mi modelo Nika",
    element: "Rubber",
    role: "main",
    abilities: ["Gear 5", "Liberación", "Haki del Conquistador"]
  },
  {
    id: "op-magellan",
    name: "Magellan",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Impel Down",
    imageUrl: "/images/characters/op-magellan.webp",
    description: "Director de Impel Down, usuario del veneno",
    haki: true,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: ["Armament"],
    devilFruit: "Doku Doku no Mi",
    element: "Poison",
    role: "supporting",
    abilities: ["Veneno letal", "Hidra venenosa", "Justicia carcelaria"]
  },
  {
    id: "op-makino",
    name: "Makino",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Bar de Foosha",
    imageUrl: "/images/characters/op-makino.webp",
    description: "Dueña del bar en Villa Foosha, figura maternal",
    haki: false,
    bounty: null,
    origin: "Villa Foosha",
    hakiTypes: [],
    devilFruit: null,
    element: "Care",
    role: "supporting",
    abilities: ["Cuidado maternal", "Cooking", "Bondad"]
  },
  {
    id: "op-mansherry",
    name: "Princess Mansherry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino Tontatta",
    imageUrl: "/images/characters/op-mansherry.webp",
    description: "Princesa de los Tontatta, usuaria de curación",
    haki: false,
    bounty: null,
    origin: "Dressrosa",
    hakiTypes: [],
    devilFruit: "Chiyu Chiyu no Mi",
    element: "Heal",
    role: "supporting",
    abilities: ["Curación milagrosa", "Liderazgo enano", "Compasión"]
  },
  {
    id: "op-marco",
    name: "Marco",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Barbablanca",
    imageUrl: "/images/characters/op-marco.webp",
    description: "1er Comandante de Barbablanca, el Fénix",
    haki: true,
    bounty: 1374000000,
    origin: "Aldea Sphinx",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Tori Tori no Mi modelo fenix",
    element: "Phoenix",
    role: "main",
    abilities: ["Regeneración", "Vuelo", "Llamas curativas"]
  },
  {
    id: "op-marcusmars",
    name: "Saint Marcus Mars",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-marcusmars.webp",
    description: "Member of the Cinco Ancianos",
    haki: true,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Poder mundial", "Autoridad suprema", "Conocimiento oculto"]
  },
  {
    id: "op-merry",
    name: "Merry",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Villa Syrup",
    imageUrl: "/images/characters/op-merry.webp",
    description: "Mayordomo de Kaya en Villa Syrup",
    haki: false,
    bounty: null,
    origin: "Villa Syrup",
    hakiTypes: [],
    devilFruit: null,
    element: "Service",
    role: "supporting",
    abilities: ["Servicio leal", "Cuidado", "Administración"]
  },
  {
    id: "op-momonga",
    name: "Momonga",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-momonga.webp",
    description: "Vicealmirante Marina, espadachín disciplinado",
    haki: true,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima marina", "Disciplina", "Liderazgo militar"]
  },
  {
    id: "op-momonosuke",
    name: "Kozuki Momonosuke",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Shogun de Wano",
    imageUrl: "/images/characters/op-momonosuke.webp",
    description: "Shogun de Wano, hijo de Oden",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Uo Uo no Mi modelo Seiryu artificial",
    element: "Dragon",
    role: "supporting",
    abilities: ["Transformación dragón", "Liderazgo noble", "Voz de Todas las Cosas"]
  },
  {
    id: "op-monet",
    name: "Monet",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-monet.webp",
    description: "Subordinada de Doflamingo, usuaria de nieve",
    haki: false,
    bounty: null,
    origin: "North Blue",
    hakiTypes: [],
    devilFruit: "Snow-Snow Fruit",
    element: "Snow",
    role: "supporting",
    abilities: ["Control de nieve", "Vuelo", "Lealtad absoluta"]
  },
  {
    id: "op-morgans",
    name: "Big News Morgans",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "World Economic Journal",
    imageUrl: "/images/characters/op-morgans.webp",
    description: "Emperador del Inframundo, rey de las noticias",
    haki: false,
    bounty: null,
    origin: "Sky Island",
    hakiTypes: [],
    devilFruit: "Tori Tori no Mi modelo albatros",
    element: "News",
    role: "supporting",
    abilities: ["Periodismo mundial", "Vuelo", "Información"]
  },
  {
    id: "op-moria",
    name: "Gecko Moria",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark Pirates",
    imageUrl: "/images/characters/op-moria.webp",
    description: "Ex-Warlord, señor de las sombras",
    haki: false,
    bounty: 320000000,
    origin: "West Blue",
    hakiTypes: [],
    devilFruit: "Shadow-Shadow Fruit",
    element: "Shadow",
    role: "supporting",
    abilities: ["Control de sombras", "Zombis", "Pesadillas"]
  },
  {
    id: "op-nami",
    name: "Nami",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-nami.webp",
    description: "Navegante de los Piratesl Sombrero de Paja",
    haki: false,
    bounty: 366000000,
    origin: "Cocoyasi Village",
    hakiTypes: [],
    devilFruit: null,
    element: "Weather",
    role: "main",
    abilities: ["Climatact", "Navegación suprema", "Cartografía"]
  },
  {
    id: "op-neptune",
    name: "Neptune",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rey Isla Gyojin",
    imageUrl: "/images/characters/op-neptune.webp",
    description: "Rey de la Isla Gyojin, padre de Shirahoshi",
    haki: true,
    bounty: null,
    origin: "Fish-Man Island",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Water",
    role: "supporting",
    abilities: ["Karate Gyojin real", "Leadership", "Diplomacia"]
  },
  {
    id: "op-nojiko",
    name: "Nojiko",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Cocoyasi Village",
    imageUrl: "/images/characters/op-nojiko.webp",
    description: "Hermana adoptiva de Nami",
    haki: false,
    bounty: null,
    origin: "Cocoyasi Village",
    hakiTypes: [],
    devilFruit: null,
    element: "Care",
    role: "supporting",
    abilities: ["Cuidado familiar", "Agricultura", "Apoyo emocional"]
  },
  {
    id: "op-nusjuro",
    name: "Saint Nusjuro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-nusjuro.webp",
    description: "Member of the Cinco Ancianos",
    haki: true,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Autoridad mundial", "Esgrima ancestral", "Poder oculto"]
  },
  {
    id: "op-oars",
    name: "Oars",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-oars.webp",
    description: "Zombi gigante animado con la sombra de Luffy",
    haki: false,
    bounty: null,
    origin: "Pais Antiguos Gigantes",
    hakiTypes: [],
    devilFruit: null,
    element: "Giant",
    role: "supporting",
    abilities: ["Fuerza colosal", "Técnicas de Luffy", "Resistencia zombi"]
  },
  {
    id: "op-oden",
    name: "Kozuki Oden",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Roger",
    imageUrl: "/images/characters/op-oden.webp",
    description: "Señor de Wano, espadachín legendario",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: null,
    element: "Sword",
    role: "main",
    abilities: ["Oden Nitoryu", "Voz de Todas las Cosas", "Liderazgo carismático"]
  },
  {
    id: "op-orochi",
    name: "Kurozumi Orochi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Shogun de Wano",
    imageUrl: "/images/characters/op-orochi.webp",
    description: "Ex-Shogun corrupto de Wano",
    haki: false,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: [],
    devilFruit: "Hebi Hebi no Mi modelo Yamata no Orochi",
    element: "Snake",
    role: "supporting",
    abilities: ["Ocho cabezas", "Cobardía", "Manipulación"]
  },
  {
    id: "op-paulie",
    name: "Paulie",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Galley-La Company",
    imageUrl: "/images/characters/op-paulie.webp",
    description: "Capataz de Galley-La Company",
    haki: false,
    bounty: null,
    origin: "Water 7",
    hakiTypes: [],
    devilFruit: null,
    element: "Rope",
    role: "supporting",
    abilities: ["Técnicas de cuerda", "Construcción naval", "Liderazgo obrero"]
  },
  {
    id: "op-pedro",
    name: "Pedro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Nox Pirates",
    imageUrl: "/images/characters/op-pedro.webp",
    description: "Líder de los Nox Pirates, guerrero mink",
    haki: true,
    bounty: 382000000,
    origin: "Zou",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Electric",
    role: "supporting",
    abilities: ["Espada electrificada", "Sacrificio", "Liderazgo mink"]
  },
  {
    id: "op-pekoms",
    name: "Pekoms",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-pekoms.webp",
    description: "Combatiente de Big Mom, mink tortuga",
    haki: true,
    bounty: 330000000,
    origin: "Zou",
    hakiTypes: ["Armament"],
    devilFruit: "Kame Kame no Mi",
    element: "Turtle",
    role: "supporting",
    abilities: ["Defensa de tortuga", "Electro mink", "Lealtad dividida"]
  },
  {
    id: "op-pell",
    name: "Pell",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Guardia Real Arabasta",
    imageUrl: "/images/characters/op-pell.webp",
    description: "El Halcón, guardián de Arabasta",
    haki: false,
    bounty: null,
    origin: "Arabasta",
    hakiTypes: [],
    devilFruit: "Tori Tori no Mi modelo halcon",
    element: "Falcon",
    role: "supporting",
    abilities: ["Vuelo halcón", "Lealtad real", "Sacrificio heroico"]
  },
  {
    id: "op-perona",
    name: "Perona",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Thriller Bark",
    imageUrl: "/images/characters/op-perona.webp",
    description: "Princesa fantasma de Thriller Bark",
    haki: false,
    bounty: null,
    origin: "Desconocido",
    hakiTypes: [],
    devilFruit: "Hollow-Hollow Fruit",
    element: "Ghost",
    role: "supporting",
    abilities: ["Fantasmas negativos", "Proyección astral", "Pesimismo"]
  },
  {
    id: "op-raizo",
    name: "Raizo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Akazaya Nine",
    imageUrl: "/images/characters/op-raizo.webp",
    description: "Ninja de Wano, uno de los Nueve Vainas Rojas",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament"],
    devilFruit: "Maki Maki no Mi",
    element: "Scroll",
    role: "supporting",
    abilities: ["Jutsu ninja", "Pergaminos", "Lealtad samurai"]
  },
  {
    id: "op-rebecca",
    name: "Rebecca",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Familia Real Dressrosa",
    imageUrl: "/images/characters/op-rebecca.webp",
    description: "Gladiadora de Dressrosa, princesa",
    haki: true,
    bounty: null,
    origin: "Dressrosa",
    hakiTypes: ["Observation"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima defensiva", "Speed", "Bondad real"]
  },
  {
    id: "op-reiju",
    name: "Vinsmoke Reiju",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Germa 66",
    imageUrl: "/images/characters/op-reiju.webp",
    description: "Poison Pink, hermana de Sanji",
    haki: false,
    bounty: null,
    origin: "Reino Germa",
    hakiTypes: [],
    devilFruit: null,
    element: "Poison",
    role: "supporting",
    abilities: ["Inmunidad veneno", "Absorción toxinas", "Compasión oculta"]
  },
  {
    id: "op-riku",
    name: "Riku Doldo III",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Rey de Dressrosa",
    imageUrl: "/images/characters/op-riku.webp",
    description: "Rey legítimo de Dressrosa",
    haki: true,
    bounty: null,
    origin: "Dressrosa",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima real", "Liderazgo noble", "Justicia"]
  },
  {
    id: "op-robin",
    name: "Nico Robin",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-robin.webp",
    description: "Arqueóloga de los Piratesl Sombrero de Paja",
    haki: true,
    bounty: 930000000,
    origin: "Ohara",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Flower-Flower Fruit",
    element: "Flower",
    role: "main",
    abilities: ["Clonar extremidades", "Archaeology", "Poneglyphs"]
  },
  {
    id: "op-roger",
    name: "Roger",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Roger",
    imageUrl: "/images/characters/op-roger.webp",
    description: "Pirate King, iniciador de la Gran Era",
    haki: true,
    bounty: 5564800000,
    origin: "Loguetown",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: null,
    element: "Sword",
    role: "main",
    abilities: ["Voz de Todas las Cosas", "Haki supremo", "Liderazgo legendario"]
  },
  {
    id: "op-ryuma",
    name: "Ryuma",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Wano Country",
    imageUrl: "/images/characters/op-ryuma.webp",
    description: "Samurai legendario de Wano",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima legendaria", "Honor samurai", "Protección nacional"]
  },
  {
    id: "op-sabo",
    name: "Sabo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Ejercito Revolutionary",
    imageUrl: "/images/characters/op-sabo.webp",
    description: "Jefe de Estado Mayor del Ejército Revolutionary",
    haki: true,
    bounty: 602000000,
    origin: "Reino Goa",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Flame-Flame Fruit",
    element: "Fire",
    role: "main",
    abilities: ["Puño de fuego", "Garra de dragón", "Revolución"]
  },
  {
    id: "op-sakazuki",
    name: "Sakazuki",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-sakazuki.webp",
    description: "Almirante de la Flota, usuario del magma",
    haki: true,
    bounty: null,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Magma-Magma Fruit",
    element: "Magma",
    role: "main",
    abilities: ["Magma devastador", "Justicia absoluta", "Puño de meteoro"]
  },
  {
    id: "op-saldeath",
    name: "Saldeath",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Impel Down",
    imageUrl: "/images/characters/op-saldeath.webp",
    description: "Guardián de Impel Down",
    haki: false,
    bounty: null,
    origin: "Impel Down",
    hakiTypes: [],
    devilFruit: null,
    element: "Fire",
    role: "supporting",
    abilities: ["Lanzallamas", "Guardia carcelaria", "Disciplina"]
  },
  {
    id: "op-sanji",
    name: "Vinsmoke Sanji",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-sanji.webp",
    description: "Cocinero de los Piratesl Sombrero de Paja",
    haki: true,
    bounty: 1032000000,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Fire",
    role: "main",
    abilities: ["Pierna del diablo", "Cocina suprema", "Caballerosidad"]
  },
  {
    id: "op-saturn",
    name: "Saint Saturn",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Gorosei",
    imageUrl: "/images/characters/op-saturn.webp",
    description: "Member of the Cinco Ancianos",
    haki: true,
    bounty: null,
    origin: "Mary Geoise",
    hakiTypes: [],
    devilFruit: null,
    element: "Elder",
    role: "supporting",
    abilities: ["Autoridad suprema", "Poder oculto", "Control mundial"]
  },
  {
    id: "op-sengoku",
    name: "Sengoku",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-sengoku.webp",
    description: "Ex-Almirante de la Flota, el Buda",
    haki: true,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Hito Hito no Mi modelo daibutsu",
    element: "Buddha",
    role: "supporting",
    abilities: ["Forma Buda dorada", "Ondas de choque", "Estrategia militar"]
  },
  {
    id: "op-shanks",
    name: "Akagami no Shanks",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Pelirrojo",
    imageUrl: "/images/characters/op-shanks.webp",
    description: "Emperador del Mar, mentor de Luffy",
    haki: true,
    bounty: 4048900000,
    origin: "West Blue",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: null,
    element: "Sword",
    role: "main",
    abilities: ["Haki supremo", "Esgrima divina", "Liderazgo carismático"]
  },
  {
    id: "op-shiki",
    name: "Shiki",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Golden Lion Pirates",
    imageUrl: "/images/characters/op-shiki.webp",
    description: "León Dorado, rival de Roger",
    haki: true,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Fuwa Fuwa no Mi",
    element: "Float",
    role: "supporting",
    abilities: ["Levitación", "Espadas en piernas", "Ambición imperial"]
  },
  {
    id: "op-shimotsuki",
    name: "Shimotsuki Yasuie",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Wano Country",
    imageUrl: "/images/characters/op-shimotsuki.webp",
    description: "Ex-Daimyo de Hakumai, padre adoptivo de Toko",
    haki: false,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: [],
    devilFruit: null,
    element: "Smile",
    role: "supporting",
    abilities: ["Sacrificio noble", "Liderazgo paternal", "Endurance"]
  },
  {
    id: "op-shiryu",
    name: "Shiryu",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kurohige",
    imageUrl: "/images/characters/op-shiryu.webp",
    description: "Ex-jefe guardián de Impel Down",
    haki: true,
    bounty: null,
    origin: "Impel Down",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Clear-Clear Fruit",
    element: "Invisible",
    role: "supporting",
    abilities: ["Invisibility", "Esgrima letal", "Sed de sangre"]
  },
  {
    id: "op-shuraiya",
    name: "Shuraiya Bascùd",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marine",
    imageUrl: "/images/characters/op-shuraiya.webp",
    description: "Cazarrecompensas marino",
    haki: false,
    bounty: null,
    origin: "East Blue",
    hakiTypes: [],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Puntería experta", "Caza recompensas", "Justicia personal"]
  },
  {
    id: "op-smoothie",
    name: "Charlotte Smoothie",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-smoothie.webp",
    description: "Comandante de Big Mom, usuaria del exprimido",
    haki: true,
    bounty: 932000000,
    origin: "Totto Land",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Shibo Shibo no Mi",
    element: "Juice",
    role: "supporting",
    abilities: ["Exprimir líquidos", "Gigantismo", "Espada gigante"]
  },
  {
    id: "op-spandam",
    name: "Spandam",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "CP-0",
    imageUrl: "/images/characters/op-spandam.webp",
    description: "Ex-jefe de CP9, ahora en CP-0",
    haki: false,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: [],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Espada elefante", "Comando", "Cobardía"]
  },
  {
    id: "op-squard",
    name: "Squard",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Maelstrom Spider Pirates",
    imageUrl: "/images/characters/op-squard.webp",
    description: "Capitán aliado de Barbablanca",
    haki: true,
    bounty: 210000000,
    origin: "New World",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Espada gigante", "Traición", "Lealtad recuperada"]
  },
  {
    id: "op-sugar",
    name: "Sugar",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-sugar.webp",
    description: "Ejecutiva de Doflamingo, usuaria de juguetes",
    haki: false,
    bounty: null,
    origin: "North Blue",
    hakiTypes: [],
    devilFruit: "Hobby-Hobby Fruit",
    element: "Toy",
    role: "supporting",
    abilities: ["Conversión juguete", "Borrado memoria", "Juventud eterna"]
  },
  {
    id: "op-toko",
    name: "Toko",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Wano Country",
    imageUrl: "/images/characters/op-toko.webp",
    description: "Niña de Wano, hija adoptiva de Yasuie",
    haki: false,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: [],
    devilFruit: null,
    element: "Smile",
    role: "supporting",
    abilities: ["Risa constante", "Inocencia", "Amor filial"]
  },
  {
    id: "op-trebol",
    name: "Trebol",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-trebol.webp",
    description: "Ejecutivo de Doflamingo, usuario pegajoso",
    haki: true,
    bounty: 99000000,
    origin: "North Blue",
    hakiTypes: ["Armament"],
    devilFruit: "Stick-Stick Fruit",
    element: "Sticky",
    role: "supporting",
    abilities: ["Sustancia pegajosa", "Explosiones", "Manipulación"]
  },
  {
    id: "op-tsuru",
    name: "Tsuru",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-tsuru.webp",
    description: "Vicealmirante veterana, usuaria del lavado",
    haki: true,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Woshu Woshu no Mi",
    element: "Wash",
    role: "supporting",
    abilities: ["Lavar y tender", "Strategy", "Veteranía"]
  },
  {
    id: "op-usopp",
    name: "Usopp",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-usopp.webp",
    description: "Francotirador de los Piratesl Sombrero de Paja",
    haki: true,
    bounty: 500000000,
    origin: "Villa Syrup",
    hakiTypes: ["Observation"],
    devilFruit: null,
    element: "Plant",
    role: "main",
    abilities: ["Francotirador supremo", "Pop Greens", "Valentía gradual"]
  },
  {
    id: "op-vander",
    name: "Vander Decken IX",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Flying Pirates",
    imageUrl: "/images/characters/op-vander.webp",
    description: "Capitán usuario del objetivo",
    haki: false,
    bounty: null,
    origin: "Fish-Man Island",
    hakiTypes: [],
    devilFruit: "Mark-Mark Fruit",
    element: "Target",
    role: "supporting",
    abilities: ["Objetivo automático", "Persecución", "Obsesión"]
  },
  {
    id: "op-vergo",
    name: "Vergo",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Donquixote Pirates",
    imageUrl: "/images/characters/op-vergo.webp",
    description: "Ex-vicealmirante, agente de Doflamingo",
    haki: true,
    bounty: null,
    origin: "North Blue",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Bamboo",
    role: "supporting",
    abilities: ["Haki de cuerpo completo", "Combate bambú", "Doble agente"]
  },
  {
    id: "op-vivi",
    name: "Nefertari Vivi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Familia Real Arabasta",
    imageUrl: "/images/characters/op-vivi.webp",
    description: "Princesa de Arabasta, ex-tripulante honoraria",
    haki: false,
    bounty: null,
    origin: "Arabasta",
    hakiTypes: [],
    devilFruit: null,
    element: "Peace",
    role: "main",
    abilities: ["Diplomacia", "Liderazgo real", "Amistad eterna"]
  },
  {
    id: "op-whitebeard",
    name: "Edward Newgate",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Barbablanca",
    imageUrl: "/images/characters/op-whitebeard.webp",
    description: "Barbablanca, el Hombre Más Fuerte del Mundo",
    haki: true,
    bounty: 5046000000,
    origin: "Isla Sphinx",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Tremor-Tremor Fruit",
    element: "Earthquake",
    role: "main",
    abilities: ["Terremotos", "Haki supremo", "Paternidad pirata"]
  },
  {
    id: "op-yamato",
    name: "Yamato",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Samurai de Wano",
    imageUrl: "/images/characters/op-yamato.webp",
    description: "Hijo de Kaido, admirador de Oden",
    haki: true,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: "Inu Inu no Mi modelo okuchi no makami",
    element: "Wolf",
    role: "main",
    abilities: ["Transformación lobo", "Hielo sagrado", "Voluntad de Oden"]
  },
  {
    id: "op-yassop",
    name: "Yassop",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Pelirrojo",
    imageUrl: "/images/characters/op-yassop.webp",
    description: "Francotirador de Shanks, padre de Usopp",
    haki: true,
    bounty: null,
    origin: "Villa Syrup",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: null,
    element: "Gun",
    role: "supporting",
    abilities: ["Puntería perfecta", "Sniper", "Abandono paternal"]
  },
  {
    id: "op-zoro",
    name: "Zoro",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Piratesl Sombrero de Paja",
    imageUrl: "/images/characters/op-zoro.webp",
    description: "Espadachín de los Piratesl Sombrero de Paja",
    haki: true,
    bounty: 1111000000,
    origin: "East Blue",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: null,
    element: "Sword",
    role: "main",
    abilities: ["Three-sword style", "Haki", "Superhuman strength"]
  },
  {
    id: "op-smoker",
    name: "Smoker",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-smoker.webp",
    description: "Vicealmirante de la Marina, usuario de humo",
    haki: true,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Smoke-Smoke Fruit",
    element: "Smoke",
    role: "supporting",
    abilities: ["Control de humo", "Haki", "Liderazgo Marina"]
  },
  {
    id: "op-tashigi",
    name: "Tashigi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Marina",
    imageUrl: "/images/characters/op-tashigi.webp",
    description: "Capitana de la Marina, coleccionista de espadas",
    haki: true,
    bounty: null,
    origin: "East Blue",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Sword",
    role: "supporting",
    abilities: ["Esgrima", "Colección de espadas", "Haki"]
  },
  {
    id: "op-pudding",
    name: "Pudding",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Big Mom",
    imageUrl: "/images/characters/op-pudding.webp",
    description: "35ta hija de Big Mom, usuaria de la memoria",
    haki: false,
    bounty: null,
    origin: "Totto Land",
    hakiTypes: [],
    devilFruit: "Memory-Memory Fruit",
    element: "Memory",
    role: "supporting",
    abilities: ["Manipulación de memoria", "Cooking", "Tercer ojo"]
  },
  {
    id: "op-viola",
    name: "Viola",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino de Dressrosa",
    imageUrl: "/images/characters/op-viola.webp",
    description: "Princesa de Dressrosa, usuaria de visión",
    haki: false,
    bounty: null,
    origin: "Dressrosa",
    hakiTypes: [],
    devilFruit: "Stare-Stare Fruit",
    element: "Vision",
    role: "supporting",
    abilities: ["Visión telescópica", "Lágrimas de ballena", "Espionaje"]
  },
  {
    id: "op-tama",
    name: "Tama",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pueblo de Wano",
    imageUrl: "/images/characters/op-tama.webp",
    description: "Niña de Wano con poder sobre animales",
    haki: false,
    bounty: null,
    origin: "Wano Country",
    hakiTypes: [],
    devilFruit: "Kibi Kibi no Mi",
    element: "Animal",
    role: "supporting",
    abilities: ["Control de animales", "Dango", "Supervivencia"]
  },
  {
    id: "op-rayleigh",
    name: "Rayleigh",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Roger",
    imageUrl: "/images/characters/op-rayleigh.webp",
    description: "Mano derecha del Pirate King",
    haki: true,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: ["Armament", "Observation", "Conqueror"],
    devilFruit: null,
    element: "Sword",
    role: "main",
    abilities: ["Haki supremo", "Espadachín legendario", "Entrenamiento"]
  },
  {
    id: "op-queen",
    name: "Queen",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kaido",
    imageUrl: "/images/characters/op-queen.webp",
    description: "Plaga de los Pirates las Bestias",
    haki: true,
    bounty: 1320000000,
    origin: "North Blue",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Dragon-Dragon Fruit",
    element: "Dinosaur",
    role: "supporting",
    abilities: ["Forma de Brachiosaurus", "Ciencia", "Virus"]
  },
  {
    id: "op-shirahoshi",
    name: "Shirahoshi",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino de Ryugu",
    imageUrl: "/images/characters/op-shirahoshi.webp",
    description: "Princesa sirena, Arma Ancestral Poseidon",
    haki: false,
    bounty: null,
    origin: "Fishman Island",
    hakiTypes: [],
    devilFruit: null,
    element: "Sea",
    role: "supporting",
    abilities: ["Control de Reyes Marinos", "Arma Ancestral", "Princesa"]
  },
  {
    id: "op-uta",
    name: "Uta",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Artista",
    imageUrl: "/images/characters/op-uta.webp",
    description: "Cantante mundialmente famosa, hija adoptiva de Shanks",
    haki: false,
    bounty: null,
    origin: "Elegia",
    hakiTypes: [],
    devilFruit: "Uta Uta no Mi",
    element: "Music",
    role: "main",
    abilities: ["Mundo de canciones", "Voz divina", "Control mental"]
  },
  {
    id: "op-wapol",
    name: "Wapol",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Reino de Drum",
    imageUrl: "/images/characters/op-wapol.webp",
    description: "Ex-rey de Drum Island, usuario de devorar",
    haki: false,
    bounty: null,
    origin: "Drum Kingdom",
    hakiTypes: [],
    devilFruit: "Baku Baku no Mi",
    element: "Metal",
    role: "supporting",
    abilities: ["Devorar todo", "Wapometal", "Transformation"]
  },
  {
    id: "op-zeff",
    name: "Zeff",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Baratie",
    imageUrl: "/images/characters/op-zeff.webp",
    description: "Chef del Baratie, mentor de Sanji",
    haki: false,
    bounty: null,
    origin: "East Blue",
    hakiTypes: [],
    devilFruit: null,
    element: "Cooking",
    role: "supporting",
    abilities: ["Cocina suprema", "Pierna roja", "Entrenamiento culinario"]
  },
  {
    id: "op-urouge",
    name: "Urouge",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates los Monjes Caídos",
    imageUrl: "/images/characters/op-urouge.webp",
    description: "Monje Loco de la Peor Generación",
    haki: true,
    bounty: 108000000,
    origin: "Cielo",
    hakiTypes: ["Armament"],
    devilFruit: null,
    element: "Strength",
    role: "supporting",
    abilities: ["Conversión de daño", "Fuerza masiva", "Endurance"]
  },
  {
    id: "op-ulti",
    name: "Ulti",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Pirates Kaido",
    imageUrl: "/images/characters/op-ulti.webp",
    description: "Tobiroppo de los Pirates las Bestias",
    haki: true,
    bounty: 400000000,
    origin: "Wano Country",
    hakiTypes: ["Armament", "Observation"],
    devilFruit: "Dragon-Dragon Fruit",
    element: "Dinosaur",
    role: "supporting",
    abilities: ["Forma de Pachycephalosaurus", "Cabezazos", "Speed"]
  },
  {
    id: "op-zunesha",
    name: "Zunesha",
    anime: "One Piece",
    animeId: "onepiece",
    crew: "Zou Island",
    imageUrl: "/images/characters/op-zunesha.webp",
    description: "Elefante milenario que lleva la isla de Zou",
    haki: false,
    bounty: null,
    origin: "Grand Line",
    hakiTypes: [],
    devilFruit: null,
    element: "Elephant",
    role: "supporting",
    abilities: ["Tamaño colosal", "Voz de las cosas", "Carga de isla"]
  }
];

// FUNCIONES DE BÚSQUEDA ACTUALIZADAS
export const getCharactersByBirthPlace = (place: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.origin.includes(place));
};

export const getCharactersByCrew = (crew: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => 
    char.crew.toLowerCase().includes(crew.toLowerCase())
  );
};

export const getCharactersByBountyRange = (min: number, max: number): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => {
    if (char.bounty === null) return false;
    return char.bounty >= min && char.bounty <= max;
  });
};

export const getCharactersWithHaki = (hakiType?: string): AnimeCharacter[] => {
  if (!hakiType) return ANIME_CHARACTERS.filter(char => char.haki);
  
  return ANIME_CHARACTERS.filter(char => 
    char.hakiTypes.some(type => type.toLowerCase().includes(hakiType.toLowerCase()))
  );
};

export const getCharactersWithDevilFruit = (): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.devilFruit !== null);
};

export const getCharactersByRole = (role: 'main' | 'supporting'): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.role === role);
};

export const getRandomCharacter = (): AnimeCharacter => {
  const randomIndex = Math.floor(Math.random() * ANIME_CHARACTERS.length);
  return ANIME_CHARACTERS[randomIndex];
};

export const getCharacterByName = (name: string): AnimeCharacter | undefined => {
  return ANIME_CHARACTERS.find(char => 
    char.name.toLowerCase().includes(name.toLowerCase()) ||
    char.nameEnglish?.toLowerCase().includes(name.toLowerCase())
  );
};

export const getCharactersByAnime = (animeId: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(char => char.animeId === animeId);
};

export const getOnePieceCharacters = (): AnimeCharacter[] => {
  return getCharactersByAnime('onepiece');
};

// Helper functions for filtering by new characteristics
export const getCharactersByBounty = (minBounty?: number, maxBounty?: number): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => {
    if (character.bounty === null) return false;
    if (minBounty && character.bounty < minBounty) return false;
    if (maxBounty && character.bounty > maxBounty) return false;
    return true;
  });
};

export const getCharactersByOrigin = (origin: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    character.origin.toLowerCase().includes(origin.toLowerCase())
  );
};

export const getCharactersByHakiType = (hakiType: string): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    character.hakiTypes.some(haki => 
      haki.toLowerCase().includes(hakiType.toLowerCase())
    )
  );
};

export const getCharactersByDevilFruit = (fruitName?: string): AnimeCharacter[] => {
  if (fruitName) {
    return ANIME_CHARACTERS.filter(character => 
      character.devilFruit && 
      character.devilFruit.toLowerCase().includes(fruitName.toLowerCase())
    );
  }
  // Return characters with any devil fruit
  return ANIME_CHARACTERS.filter(character => 
    character.devilFruit && character.devilFruit !== null
  );
};

export const getCharactersWithoutDevilFruit = (): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    character.devilFruit === null
  );
};

export const getCharactersByHakiTypes = (hakiTypes: string[]): AnimeCharacter[] => {
  return ANIME_CHARACTERS.filter(character => 
    hakiTypes.every(haki => 
      character.hakiTypes.some(charHaki => 
        charHaki.toLowerCase().includes(haki.toLowerCase())
      )
    )
  );
};

export const getTopBounties = (limit: number = 10): AnimeCharacter[] => {
  return ANIME_CHARACTERS
    .filter(character => character.bounty !== null)
    .sort((a, b) => (b.bounty || 0) - (a.bounty || 0))
    .slice(0, limit);
};

export const getCharacterStats = () => {
  const total = ANIME_CHARACTERS.length;
  const withBounty = ANIME_CHARACTERS.filter(c => c.bounty !== null).length;
  const withDevilFruit = ANIME_CHARACTERS.filter(c => c.devilFruit !== null).length;
  const withHaki = ANIME_CHARACTERS.filter(c => c.hakiTypes.length > 0).length;
  const conquerorHaki = ANIME_CHARACTERS.filter(c => 
    c.hakiTypes.some(h => h.toLowerCase().includes('conqueror'))
  ).length;

  return {
    total,
    withBounty,
    withDevilFruit,
    withHaki,
    conquerorHaki,
    withoutBounty: total - withBounty,
    withoutDevilFruit: total - withDevilFruit,
    withoutHaki: total - withHaki
  };
};
